// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.data.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "KAMPAGNEN")
public class KampagneEntity extends AuditingEntity {
	@Column(name = "NAME")
	private String name;
	@Column(name = "GRUPPE_ID")
	private int gruppeId;


	public String getName() {
		return this.name;
	}


	public int getGruppeId() {
		return this.gruppeId;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setGruppeId(final int gruppeId) {
		this.gruppeId = gruppeId;
	}
}
