CREATE TABLE USERS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	PASSWORD varchar(60),
	TOKEN varchar(64),
	GRUPPE_ID INTEGER NOT NULL,
	CREATED_DATE DATETIME  NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE GRUPPEN(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);