CREATE TABLE LAGERORT(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	HELDID INTEGER NOT NULL,
	NOTIZ MEDIUMTEXT,
	PRIMARY KEY(ID)
);

CREATE TABLE GEGENSTAND_TO_LAGERORT(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  LAGERORT INTEGER NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  AMOUNT INTEGER NOT NULL,
  PRIMARY KEY(ID)
);
