//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.11 at 12:16:13 PM CEST 
//


package de.failender.heldensoftware.xml.heldenliste;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}heldenid"/>
 *         &lt;element ref="{}getName"/>
 *         &lt;element ref="{}heldenkey"/>
 *         &lt;element ref="{}heldlastchange"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heldenid",
    "name",
    "heldenkey",
    "heldlastchange"
})
@XmlRootElement(name = "held")
public class Held {

    @XmlElement(required = true)
    protected BigInteger heldenid;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BigInteger heldenkey;
    @XmlElement(required = true)
    protected BigInteger heldlastchange;

    /**
     * Gets the value of the heldenid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeldenid() {
        return heldenid;
    }

    /**
     * Sets the value of the heldenid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeldenid(BigInteger value) {
        this.heldenid = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the heldenkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeldenkey() {
        return heldenkey;
    }

    /**
     * Sets the value of the heldenkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeldenkey(BigInteger value) {
        this.heldenkey = value;
    }

    /**
     * Gets the value of the heldlastchange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeldlastchange() {
        return heldlastchange;
    }

    /**
     * Sets the value of the heldlastchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeldlastchange(BigInteger value) {
        this.heldlastchange = value;
    }

}
