//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxbGenerated.datenxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Kontrollwert_QNAME = new QName("", "kontrollwert");
    private final static QName _Angelegt1_QNAME = new QName("", "angelegt1");
    private final static QName _Angelegt2_QNAME = new QName("", "angelegt2");
    private final static QName _Groesse_QNAME = new QName("", "groesse");
    private final static QName _Professionmod_QNAME = new QName("", "professionmod");
    private final static QName _Ladezeit_QNAME = new QName("", "ladezeit");
    private final static QName _Einzelpreis_QNAME = new QName("", "einzelpreis");
    private final static QName _Alter_QNAME = new QName("", "alter");
    private final static QName _Rechtesbein_QNAME = new QName("", "rechtesbein");
    private final static QName _Haarfarbe_QNAME = new QName("", "haarfarbe");
    private final static QName _Mr_QNAME = new QName("", "mr");
    private final static QName _Spezialisierungen_QNAME = new QName("", "spezialisierungen");
    private final static QName _Waffentalentkurz_QNAME = new QName("", "waffentalentkurz");
    private final static QName _Muinch2_QNAME = new QName("", "muinch2");
    private final static QName _N10_QNAME = new QName("", "n10");
    private final static QName _Aspregeneration_QNAME = new QName("", "aspregeneration");
    private final static QName _Akt25_QNAME = new QName("", "akt25");
    private final static QName _N11_QNAME = new QName("", "n11");
    private final static QName _Max_QNAME = new QName("", "max");
    private final static QName _F3_QNAME = new QName("", "f3");
    private final static QName _Geschwindigkeitinklbe_QNAME = new QName("", "geschwindigkeitinklbe");
    private final static QName _F2_QNAME = new QName("", "f2");
    private final static QName _F5_QNAME = new QName("", "f5");
    private final static QName _F4_QNAME = new QName("", "f4");
    private final static QName _Initiative_QNAME = new QName("", "initiative");
    private final static QName _A1_QNAME = new QName("", "a1");
    private final static QName _Rechterarm_QNAME = new QName("", "rechterarm");
    private final static QName _A2_QNAME = new QName("", "a2");
    private final static QName _F1_QNAME = new QName("", "f1");
    private final static QName _A3_QNAME = new QName("", "a3");
    private final static QName _Namekurz_QNAME = new QName("", "namekurz");
    private final static QName _F0_QNAME = new QName("", "f0");
    private final static QName _Dk_QNAME = new QName("", "dk");
    private final static QName _Ausweichen_QNAME = new QName("", "ausweichen");
    private final static QName _Gesamtgewicht_QNAME = new QName("", "gesamtgewicht");
    private final static QName _Namemitkommentar_QNAME = new QName("", "namemitkommentar");
    private final static QName _Datum_QNAME = new QName("", "datum");
    private final static QName _Waehrung_QNAME = new QName("", "waehrung");
    private final static QName _Grosserkommentar_QNAME = new QName("", "grosserkommentar");
    private final static QName _Augenfarbe_QNAME = new QName("", "augenfarbe");
    private final static QName _Anmerkung_QNAME = new QName("", "anmerkung");
    private final static QName _Meisterhandwerk_QNAME = new QName("", "meisterhandwerk");
    private final static QName _Zauberdauer_QNAME = new QName("", "zauberdauer");
    private final static QName _Probe_QNAME = new QName("", "probe");
    private final static QName _N9_QNAME = new QName("", "n9");
    private final static QName _N8_QNAME = new QName("", "n8");
    private final static QName _Grossemeditation_QNAME = new QName("", "grossemeditation");
    private final static QName _N7_QNAME = new QName("", "n7");
    private final static QName _Modi_QNAME = new QName("", "modi");
    private final static QName _N6_QNAME = new QName("", "n6");
    private final static QName _N5_QNAME = new QName("", "n5");
    private final static QName _N4_QNAME = new QName("", "n4");
    private final static QName _A0_QNAME = new QName("", "a0");
    private final static QName _Fingerfertigkeit_QNAME = new QName("", "fingerfertigkeit");
    private final static QName _N3_QNAME = new QName("", "n3");
    private final static QName _Akt33_QNAME = new QName("", "akt33");
    private final static QName _Ruecken_QNAME = new QName("", "ruecken");
    private final static QName _N2_QNAME = new QName("", "n2");
    private final static QName _Dauer_QNAME = new QName("", "dauer");
    private final static QName _N1_QNAME = new QName("", "n1");
    private final static QName _Tpmod_QNAME = new QName("", "tpmod");
    private final static QName _N0_QNAME = new QName("", "n0");
    private final static QName _Pasprueckkaufbar_QNAME = new QName("", "pasprueckkaufbar");
    private final static QName _Tpinkl_QNAME = new QName("", "tpinkl");
    private final static QName _Leregeneration_QNAME = new QName("", "leregeneration");
    private final static QName _Typ_QNAME = new QName("", "typ");
    private final static QName _Pa_QNAME = new QName("", "pa");
    private final static QName _Start_QNAME = new QName("", "start");
    private final static QName _Genutzt_QNAME = new QName("", "genutzt");
    private final static QName _Bfakt_QNAME = new QName("", "bfakt");
    private final static QName _Kampftalent_QNAME = new QName("", "kampftalent");
    private final static QName _Angelegt_QNAME = new QName("", "angelegt");
    private final static QName _Leittalent_QNAME = new QName("", "leittalent");
    private final static QName _Sozialstatus_QNAME = new QName("", "sozialstatus");
    private final static QName _Möglich_QNAME = new QName("", "m\u00f6glich");
    private final static QName _Zauberquellen_QNAME = new QName("", "zauberquellen");
    private final static QName _Waffentalent_QNAME = new QName("", "waffentalent");
    private final static QName _Wm_QNAME = new QName("", "wm");
    private final static QName _Mod_QNAME = new QName("", "mod");
    private final static QName _Ausvornachteile_QNAME = new QName("", "ausvornachteile");
    private final static QName _Wirkung_QNAME = new QName("", "wirkung");
    private final static QName _FernkampfBasis_QNAME = new QName("", "fernkampf-basis");
    private final static QName _Textkurz_QNAME = new QName("", "textkurz");
    private final static QName _Istnachteil_QNAME = new QName("", "istnachteil");
    private final static QName _Kosten_QNAME = new QName("", "kosten");
    private final static QName _Gesamtschutz_QNAME = new QName("", "gesamtschutz");
    private final static QName _Geburtstag_QNAME = new QName("", "geburtstag");
    private final static QName _Variante_QNAME = new QName("", "variante");
    private final static QName _Parade_QNAME = new QName("", "parade");
    private final static QName _Mirakelminus_QNAME = new QName("", "mirakelminus");
    private final static QName _Gekauft_QNAME = new QName("", "gekauft");
    private final static QName _Geldkreise_QNAME = new QName("", "geldkreise");
    private final static QName _Frei_QNAME = new QName("", "frei");
    private final static QName _Attacke_QNAME = new QName("", "attacke");
    private final static QName _Istgabe_QNAME = new QName("", "istgabe");
    private final static QName _Ausweichenausweichenmod_QNAME = new QName("", "ausweichenausweichenmod");
    private final static QName _Wirkungsdauer_QNAME = new QName("", "wirkungsdauer");
    private final static QName _Beschreibung_QNAME = new QName("", "beschreibung");
    private final static QName _Magisch_QNAME = new QName("", "magisch");
    private final static QName _Rsmodell_QNAME = new QName("", "rsmodell");
    private final static QName _Lebensenergie_QNAME = new QName("", "lebensenergie");
    private final static QName _Metatalent_QNAME = new QName("", "metatalent");
    private final static QName _Charisma_QNAME = new QName("", "charisma");
    private final static QName _Merkmale_QNAME = new QName("", "merkmale");
    private final static QName _Stand_QNAME = new QName("", "stand");
    private final static QName _Nameausfuehrlich_QNAME = new QName("", "nameausfuehrlich");
    private final static QName _Heldenversion_QNAME = new QName("", "heldenversion");
    private final static QName _Akt_QNAME = new QName("", "akt");
    private final static QName _Gewicht_QNAME = new QName("", "gewicht");
    private final static QName _Reichweite_QNAME = new QName("", "reichweite");
    private final static QName _Gesamtwertinsilberstuecken_QNAME = new QName("", "gesamtwertinsilberstuecken");
    private final static QName _At_QNAME = new QName("", "at");
    private final static QName _Metatalente_QNAME = new QName("", "metatalente");
    private final static QName _Mut_QNAME = new QName("", "mut");
    private final static QName _Namemitvariante_QNAME = new QName("", "namemitvariante");
    private final static QName _Nameausfuehrlichmitprobe_QNAME = new QName("", "nameausfuehrlichmitprobe");
    private final static QName _Intuition_QNAME = new QName("", "intuition");
    private final static QName _Ausdauer_QNAME = new QName("", "ausdauer");
    private final static QName _Gesamtzonenschutz_QNAME = new QName("", "gesamtzonenschutz");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Uhrzeit_QNAME = new QName("", "uhrzeit");
    private final static QName _Magieresistenz_QNAME = new QName("", "magieresistenz");
    private final static QName _Schriftmuttersprache_QNAME = new QName("", "schriftmuttersprache");
    private final static QName _Gewandtheit_QNAME = new QName("", "gewandtheit");
    private final static QName _Lang_QNAME = new QName("", "lang");
    private final static QName _Grundlage_QNAME = new QName("", "grundlage");
    private final static QName _Geschlecht_QNAME = new QName("", "geschlecht");
    private final static QName _Kopf_QNAME = new QName("", "kopf");
    private final static QName _BildPfad_QNAME = new QName("", "bildPfad");
    private final static QName _Hauszauberformatiert_QNAME = new QName("", "hauszauberformatiert");
    private final static QName _Brust_QNAME = new QName("", "brust");
    private final static QName _Grad_QNAME = new QName("", "grad");
    private final static QName _Namenaufseiten_QNAME = new QName("", "namenaufseiten");
    private final static QName _Bereich_QNAME = new QName("", "bereich");
    private final static QName _Istschlechteeigenschaft_QNAME = new QName("", "istschlechteeigenschaft");
    private final static QName _Lernkomplexität_QNAME = new QName("", "lernkomplexit\u00e4t");
    private final static QName _Rs_QNAME = new QName("", "rs");
    private final static QName _Spalte2_QNAME = new QName("", "spalte2");
    private final static QName _Arten_QNAME = new QName("", "arten");
    private final static QName _Rest_QNAME = new QName("", "rest");
    private final static QName _Sprachkomplexität_QNAME = new QName("", "sprachkomplexit\u00e4t");
    private final static QName _Titel_QNAME = new QName("", "titel");
    private final static QName _Bauch_QNAME = new QName("", "bauch");
    private final static QName _Ini_QNAME = new QName("", "ini");
    private final static QName _Repräsentation_QNAME = new QName("", "repr\u00e4sentation");
    private final static QName _Ausweichenakrobatikmod_QNAME = new QName("", "ausweichenakrobatikmod");
    private final static QName _Nummer_QNAME = new QName("", "nummer");
    private final static QName _Koerperkraft_QNAME = new QName("", "koerperkraft");
    private final static QName _Gesamt_QNAME = new QName("", "gesamt");
    private final static QName _Kultur_QNAME = new QName("", "kultur");
    private final static QName _Rasse_QNAME = new QName("", "rasse");
    private final static QName _So_QNAME = new QName("", "so");
    private final static QName _Probenwerte_QNAME = new QName("", "probenwerte");
    private final static QName _Aussonderfertigkeiten_QNAME = new QName("", "aussonderfertigkeiten");
    private final static QName _Bezeichner_QNAME = new QName("", "bezeichner");
    private final static QName _Astralenergie_QNAME = new QName("", "astralenergie");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _Geweiht_QNAME = new QName("", "geweiht");
    private final static QName _Aktinklrueckkaufbarepasp_QNAME = new QName("", "aktinklrueckkaufbarepasp");
    private final static QName _Klugheit_QNAME = new QName("", "klugheit");
    private final static QName _Be_QNAME = new QName("", "be");
    private final static QName _Behinderung_QNAME = new QName("", "behinderung");
    private final static QName _Konstitution_QNAME = new QName("", "konstitution");
    private final static QName _Bf_QNAME = new QName("", "bf");
    private final static QName _Gesamtpreis_QNAME = new QName("", "gesamtpreis");
    private final static QName _Muttersprache_QNAME = new QName("", "muttersprache");
    private final static QName _Bfmin_QNAME = new QName("", "bfmin");
    private final static QName _Kommentar_QNAME = new QName("", "kommentar");
    private final static QName _Komplexität_QNAME = new QName("", "komplexit\u00e4t");
    private final static QName _Hauszauber_QNAME = new QName("", "hauszauber");
    private final static QName _Karmaenergie_QNAME = new QName("", "karmaenergie");
    private final static QName _Geschwindigkeit_QNAME = new QName("", "geschwindigkeit");
    private final static QName _Zweitlehrsprache_QNAME = new QName("", "zweitlehrsprache");
    private final static QName _Wundschwelle_QNAME = new QName("", "wundschwelle");
    private final static QName _Ausweichenmod_QNAME = new QName("", "ausweichenmod");
    private final static QName _Linkerarm_QNAME = new QName("", "linkerarm");
    private final static QName _Linkesbein_QNAME = new QName("", "linkesbein");
    private final static QName _Basis_QNAME = new QName("", "basis");
    private final static QName _Akt50_QNAME = new QName("", "akt50");
    private final static QName _Kaufbar_QNAME = new QName("", "kaufbar");
    private final static QName _Mirakelplus_QNAME = new QName("", "mirakelplus");
    private final static QName _Gilde_QNAME = new QName("", "gilde");
    private final static QName _Istvorteil_QNAME = new QName("", "istvorteil");
    private final static QName _Anzahl_QNAME = new QName("", "anzahl");
    private final static QName _Tp_QNAME = new QName("", "tp");
    private final static QName _Wert_QNAME = new QName("", "wert");
    private final static QName _Wertinsilberstuecken_QNAME = new QName("", "wertinsilberstuecken");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxbGenerated.datenxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sonderfertigkeit }
     * 
     */
    public Sonderfertigkeit createSonderfertigkeit() {
        return new Sonderfertigkeit();
    }

    /**
     * Create an instance of {@link Vorteil }
     * 
     */
    public Vorteil createVorteil() {
        return new Vorteil();
    }

    /**
     * Create an instance of {@link Tier }
     * 
     */
    public Tier createTier() {
        return new Tier();
    }

    /**
     * Create an instance of {@link Tier.Angriffe }
     * 
     */
    public Tier.Angriffe createTierAngriffe() {
        return new Tier.Angriffe();
    }

    /**
     * Create an instance of {@link Sonderfertigkeit.Auswahlen }
     * 
     */
    public Sonderfertigkeit.Auswahlen createSonderfertigkeitAuswahlen() {
        return new Sonderfertigkeit.Auswahlen();
    }

    /**
     * Create an instance of {@link Münze }
     * 
     */
    public Münze createMünze() {
        return new Münze();
    }

    /**
     * Create an instance of {@link Eigenschaftswerte }
     * 
     */
    public Eigenschaftswerte createEigenschaftswerte() {
        return new Eigenschaftswerte();
    }

    /**
     * Create an instance of {@link Eigenschaften }
     * 
     */
    public Eigenschaften createEigenschaften() {
        return new Eigenschaften();
    }

    /**
     * Create an instance of {@link Eigenschaftswerteastrale }
     * 
     */
    public Eigenschaftswerteastrale createEigenschaftswerteastrale() {
        return new Eigenschaftswerteastrale();
    }

    /**
     * Create an instance of {@link Eigenschaftswertezukaufbar503325 }
     * 
     */
    public Eigenschaftswertezukaufbar503325 createEigenschaftswertezukaufbar503325() {
        return new Eigenschaftswertezukaufbar503325();
    }

    /**
     * Create an instance of {@link Eigenschaftswertezukaufbar }
     * 
     */
    public Eigenschaftswertezukaufbar createEigenschaftswertezukaufbar() {
        return new Eigenschaftswertezukaufbar();
    }

    /**
     * Create an instance of {@link Sonderfertigkeiten }
     * 
     */
    public Sonderfertigkeiten createSonderfertigkeiten() {
        return new Sonderfertigkeiten();
    }

    /**
     * Create an instance of {@link Zauber }
     * 
     */
    public Zauber createZauber() {
        return new Zauber();
    }

    /**
     * Create an instance of {@link Quelle }
     * 
     */
    public Quelle createQuelle() {
        return new Quelle();
    }

    /**
     * Create an instance of {@link Fernkampfwaffen }
     * 
     */
    public Fernkampfwaffen createFernkampfwaffen() {
        return new Fernkampfwaffen();
    }

    /**
     * Create an instance of {@link Fernkampfwaffe }
     * 
     */
    public Fernkampfwaffe createFernkampfwaffe() {
        return new Fernkampfwaffe();
    }

    /**
     * Create an instance of {@link Verbilligtesonderfertigkeit }
     * 
     */
    public Verbilligtesonderfertigkeit createVerbilligtesonderfertigkeit() {
        return new Verbilligtesonderfertigkeit();
    }

    /**
     * Create an instance of {@link Stufe41 }
     * 
     */
    public Stufe41 createStufe41() {
        return new Stufe41();
    }

    /**
     * Create an instance of {@link Notizen }
     * 
     */
    public Notizen createNotizen() {
        return new Notizen();
    }

    /**
     * Create an instance of {@link Gp }
     * 
     */
    public Gp createGp() {
        return new Gp();
    }

    /**
     * Create an instance of {@link Ruestungeinfach }
     * 
     */
    public Ruestungeinfach createRuestungeinfach() {
        return new Ruestungeinfach();
    }

    /**
     * Create an instance of {@link Daten }
     * 
     */
    public Daten createDaten() {
        return new Daten();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Angaben }
     * 
     */
    public Angaben createAngaben() {
        return new Angaben();
    }

    /**
     * Create an instance of {@link Aussehen }
     * 
     */
    public Aussehen createAussehen() {
        return new Aussehen();
    }

    /**
     * Create an instance of {@link Familie }
     * 
     */
    public Familie createFamilie() {
        return new Familie();
    }

    /**
     * Create an instance of {@link Profession }
     * 
     */
    public Profession createProfession() {
        return new Profession();
    }

    /**
     * Create an instance of {@link Ap }
     * 
     */
    public Ap createAp() {
        return new Ap();
    }

    /**
     * Create an instance of {@link Stufe40 }
     * 
     */
    public Stufe40 createStufe40() {
        return new Stufe40();
    }

    /**
     * Create an instance of {@link Münzen }
     * 
     */
    public Münzen createMünzen() {
        return new Münzen();
    }

    /**
     * Create an instance of {@link Vorteile }
     * 
     */
    public Vorteile createVorteile() {
        return new Vorteile();
    }

    /**
     * Create an instance of {@link Vorteil.Auswahlen }
     * 
     */
    public Vorteil.Auswahlen createVorteilAuswahlen() {
        return new Vorteil.Auswahlen();
    }

    /**
     * Create an instance of {@link Verbilligtesonderfertigkeiten }
     * 
     */
    public Verbilligtesonderfertigkeiten createVerbilligtesonderfertigkeiten() {
        return new Verbilligtesonderfertigkeiten();
    }

    /**
     * Create an instance of {@link Talentliste }
     * 
     */
    public Talentliste createTalentliste() {
        return new Talentliste();
    }

    /**
     * Create an instance of {@link Talent }
     * 
     */
    public Talent createTalent() {
        return new Talent();
    }

    /**
     * Create an instance of {@link Zauberliste }
     * 
     */
    public Zauberliste createZauberliste() {
        return new Zauberliste();
    }

    /**
     * Create an instance of {@link Gegenstaende }
     * 
     */
    public Gegenstaende createGegenstaende() {
        return new Gegenstaende();
    }

    /**
     * Create an instance of {@link Gegenstand }
     * 
     */
    public Gegenstand createGegenstand() {
        return new Gegenstand();
    }

    /**
     * Create an instance of {@link Details }
     * 
     */
    public Details createDetails() {
        return new Details();
    }

    /**
     * Create an instance of {@link Tier.Eigenschaften }
     * 
     */
    public Tier.Eigenschaften createTierEigenschaften() {
        return new Tier.Eigenschaften();
    }

    /**
     * Create an instance of {@link Tier.Ini }
     * 
     */
    public Tier.Ini createTierIni() {
        return new Tier.Ini();
    }

    /**
     * Create an instance of {@link Verbindungen }
     * 
     */
    public Verbindungen createVerbindungen() {
        return new Verbindungen();
    }

    /**
     * Create an instance of {@link Verbindung }
     * 
     */
    public Verbindung createVerbindung() {
        return new Verbindung();
    }

    /**
     * Create an instance of {@link Kampfsets }
     * 
     */
    public Kampfsets createKampfsets() {
        return new Kampfsets();
    }

    /**
     * Create an instance of {@link Kampfset }
     * 
     */
    public Kampfset createKampfset() {
        return new Kampfset();
    }

    /**
     * Create an instance of {@link Raufen }
     * 
     */
    public Raufen createRaufen() {
        return new Raufen();
    }

    /**
     * Create an instance of {@link Ringen }
     * 
     */
    public Ringen createRingen() {
        return new Ringen();
    }

    /**
     * Create an instance of {@link Ruestungzonen }
     * 
     */
    public Ruestungzonen createRuestungzonen() {
        return new Ruestungzonen();
    }

    /**
     * Create an instance of {@link Nahkampfwaffen }
     * 
     */
    public Nahkampfwaffen createNahkampfwaffen() {
        return new Nahkampfwaffen();
    }

    /**
     * Create an instance of {@link Nahkampfwaffe }
     * 
     */
    public Nahkampfwaffe createNahkampfwaffe() {
        return new Nahkampfwaffe();
    }

    /**
     * Create an instance of {@link Tpkk }
     * 
     */
    public Tpkk createTpkk() {
        return new Tpkk();
    }

    /**
     * Create an instance of {@link Schilder }
     * 
     */
    public Schilder createSchilder() {
        return new Schilder();
    }

    /**
     * Create an instance of {@link Schild }
     * 
     */
    public Schild createSchild() {
        return new Schild();
    }

    /**
     * Create an instance of {@link Ruestungen }
     * 
     */
    public Ruestungen createRuestungen() {
        return new Ruestungen();
    }

    /**
     * Create an instance of {@link Ruestung }
     * 
     */
    public Ruestung createRuestung() {
        return new Ruestung();
    }

    /**
     * Create an instance of {@link Feld }
     * 
     */
    public Feld createFeld() {
        return new Feld();
    }

    /**
     * Create an instance of {@link Tier.Angriffe.Angriff }
     * 
     */
    public Tier.Angriffe.Angriff createTierAngriffeAngriff() {
        return new Tier.Angriffe.Angriff();
    }

    /**
     * Create an instance of {@link Sonderfertigkeit.Auswahlen.Auswahl }
     * 
     */
    public Sonderfertigkeit.Auswahlen.Auswahl createSonderfertigkeitAuswahlenAuswahl() {
        return new Sonderfertigkeit.Auswahlen.Auswahl();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kontrollwert")
    public JAXBElement<String> createKontrollwert(String value) {
        return new JAXBElement<String>(_Kontrollwert_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angelegt1")
    public JAXBElement<Boolean> createAngelegt1(Boolean value) {
        return new JAXBElement<Boolean>(_Angelegt1_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angelegt2")
    public JAXBElement<Boolean> createAngelegt2(Boolean value) {
        return new JAXBElement<Boolean>(_Angelegt2_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "groesse")
    public JAXBElement<BigInteger> createGroesse(BigInteger value) {
        return new JAXBElement<BigInteger>(_Groesse_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "professionmod")
    public JAXBElement<BigInteger> createProfessionmod(BigInteger value) {
        return new JAXBElement<BigInteger>(_Professionmod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ladezeit")
    public JAXBElement<BigInteger> createLadezeit(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ladezeit_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "einzelpreis")
    public JAXBElement<BigInteger> createEinzelpreis(BigInteger value) {
        return new JAXBElement<BigInteger>(_Einzelpreis_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alter")
    public JAXBElement<BigInteger> createAlter(BigInteger value) {
        return new JAXBElement<BigInteger>(_Alter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rechtesbein")
    public JAXBElement<BigInteger> createRechtesbein(BigInteger value) {
        return new JAXBElement<BigInteger>(_Rechtesbein_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "haarfarbe")
    public JAXBElement<String> createHaarfarbe(String value) {
        return new JAXBElement<String>(_Haarfarbe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mr")
    public JAXBElement<String> createMr(String value) {
        return new JAXBElement<String>(_Mr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spezialisierungen")
    public JAXBElement<String> createSpezialisierungen(String value) {
        return new JAXBElement<String>(_Spezialisierungen_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "waffentalentkurz")
    public JAXBElement<String> createWaffentalentkurz(String value) {
        return new JAXBElement<String>(_Waffentalentkurz_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "muinch2")
    public JAXBElement<BigInteger> createMuinch2(BigInteger value) {
        return new JAXBElement<BigInteger>(_Muinch2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n10")
    public JAXBElement<String> createN10(String value) {
        return new JAXBElement<String>(_N10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aspregeneration")
    public JAXBElement<String> createAspregeneration(String value) {
        return new JAXBElement<String>(_Aspregeneration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "akt25")
    public JAXBElement<BigInteger> createAkt25(BigInteger value) {
        return new JAXBElement<BigInteger>(_Akt25_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n11")
    public JAXBElement<String> createN11(String value) {
        return new JAXBElement<String>(_N11_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "max")
    public JAXBElement<BigInteger> createMax(BigInteger value) {
        return new JAXBElement<BigInteger>(_Max_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f3")
    public JAXBElement<String> createF3(String value) {
        return new JAXBElement<String>(_F3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geschwindigkeitinklbe")
    public JAXBElement<BigInteger> createGeschwindigkeitinklbe(BigInteger value) {
        return new JAXBElement<BigInteger>(_Geschwindigkeitinklbe_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f2")
    public JAXBElement<String> createF2(String value) {
        return new JAXBElement<String>(_F2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f5")
    public JAXBElement<String> createF5(String value) {
        return new JAXBElement<String>(_F5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f4")
    public JAXBElement<String> createF4(String value) {
        return new JAXBElement<String>(_F4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "initiative")
    public JAXBElement<Eigenschaftswerte> createInitiative(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Initiative_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a1")
    public JAXBElement<String> createA1(String value) {
        return new JAXBElement<String>(_A1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rechterarm")
    public JAXBElement<BigInteger> createRechterarm(BigInteger value) {
        return new JAXBElement<BigInteger>(_Rechterarm_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a2")
    public JAXBElement<String> createA2(String value) {
        return new JAXBElement<String>(_A2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f1")
    public JAXBElement<String> createF1(String value) {
        return new JAXBElement<String>(_F1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a3")
    public JAXBElement<String> createA3(String value) {
        return new JAXBElement<String>(_A3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "namekurz")
    public JAXBElement<String> createNamekurz(String value) {
        return new JAXBElement<String>(_Namekurz_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "f0")
    public JAXBElement<String> createF0(String value) {
        return new JAXBElement<String>(_F0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dk")
    public JAXBElement<String> createDk(String value) {
        return new JAXBElement<String>(_Dk_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausweichen")
    public JAXBElement<BigInteger> createAusweichen(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ausweichen_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamtgewicht")
    public JAXBElement<BigDecimal> createGesamtgewicht(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Gesamtgewicht_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "namemitkommentar")
    public JAXBElement<String> createNamemitkommentar(String value) {
        return new JAXBElement<String>(_Namemitkommentar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatum(String value) {
        return new JAXBElement<String>(_Datum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "waehrung")
    public JAXBElement<String> createWaehrung(String value) {
        return new JAXBElement<String>(_Waehrung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "grosserkommentar")
    public JAXBElement<Boolean> createGrosserkommentar(Boolean value) {
        return new JAXBElement<Boolean>(_Grosserkommentar_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "augenfarbe")
    public JAXBElement<String> createAugenfarbe(String value) {
        return new JAXBElement<String>(_Augenfarbe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anmerkung")
    public JAXBElement<String> createAnmerkung(String value) {
        return new JAXBElement<String>(_Anmerkung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "meisterhandwerk")
    public JAXBElement<Boolean> createMeisterhandwerk(Boolean value) {
        return new JAXBElement<Boolean>(_Meisterhandwerk_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zauberdauer")
    public JAXBElement<String> createZauberdauer(String value) {
        return new JAXBElement<String>(_Zauberdauer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "probe")
    public JAXBElement<String> createProbe(String value) {
        return new JAXBElement<String>(_Probe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n9")
    public JAXBElement<String> createN9(String value) {
        return new JAXBElement<String>(_N9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n8")
    public JAXBElement<String> createN8(String value) {
        return new JAXBElement<String>(_N8_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "grossemeditation")
    public JAXBElement<BigInteger> createGrossemeditation(BigInteger value) {
        return new JAXBElement<BigInteger>(_Grossemeditation_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n7")
    public JAXBElement<String> createN7(String value) {
        return new JAXBElement<String>(_N7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modi")
    public JAXBElement<BigInteger> createModi(BigInteger value) {
        return new JAXBElement<BigInteger>(_Modi_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n6")
    public JAXBElement<String> createN6(String value) {
        return new JAXBElement<String>(_N6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n5")
    public JAXBElement<String> createN5(String value) {
        return new JAXBElement<String>(_N5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n4")
    public JAXBElement<String> createN4(String value) {
        return new JAXBElement<String>(_N4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "a0")
    public JAXBElement<String> createA0(String value) {
        return new JAXBElement<String>(_A0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fingerfertigkeit")
    public JAXBElement<Eigenschaftswerte> createFingerfertigkeit(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Fingerfertigkeit_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n3")
    public JAXBElement<String> createN3(String value) {
        return new JAXBElement<String>(_N3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "akt33")
    public JAXBElement<BigInteger> createAkt33(BigInteger value) {
        return new JAXBElement<BigInteger>(_Akt33_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ruecken")
    public JAXBElement<BigInteger> createRuecken(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ruecken_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n2")
    public JAXBElement<String> createN2(String value) {
        return new JAXBElement<String>(_N2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dauer")
    public JAXBElement<String> createDauer(String value) {
        return new JAXBElement<String>(_Dauer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n1")
    public JAXBElement<String> createN1(String value) {
        return new JAXBElement<String>(_N1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tpmod")
    public JAXBElement<String> createTpmod(String value) {
        return new JAXBElement<String>(_Tpmod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "n0")
    public JAXBElement<String> createN0(String value) {
        return new JAXBElement<String>(_N0_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pasprueckkaufbar")
    public JAXBElement<BigInteger> createPasprueckkaufbar(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pasprueckkaufbar_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tpinkl")
    public JAXBElement<String> createTpinkl(String value) {
        return new JAXBElement<String>(_Tpinkl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "leregeneration")
    public JAXBElement<String> createLeregeneration(String value) {
        return new JAXBElement<String>(_Leregeneration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "typ")
    public JAXBElement<String> createTyp(String value) {
        return new JAXBElement<String>(_Typ_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pa")
    public JAXBElement<String> createPa(String value) {
        return new JAXBElement<String>(_Pa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start")
    public JAXBElement<BigInteger> createStart(BigInteger value) {
        return new JAXBElement<BigInteger>(_Start_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genutzt")
    public JAXBElement<BigInteger> createGenutzt(BigInteger value) {
        return new JAXBElement<BigInteger>(_Genutzt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bfakt")
    public JAXBElement<BigInteger> createBfakt(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bfakt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kampftalent")
    public JAXBElement<String> createKampftalent(String value) {
        return new JAXBElement<String>(_Kampftalent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "angelegt")
    public JAXBElement<Boolean> createAngelegt(Boolean value) {
        return new JAXBElement<Boolean>(_Angelegt_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "leittalent")
    public JAXBElement<Boolean> createLeittalent(Boolean value) {
        return new JAXBElement<Boolean>(_Leittalent_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sozialstatus")
    public JAXBElement<Eigenschaftswerte> createSozialstatus(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Sozialstatus_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "m\u00f6glich")
    public JAXBElement<Boolean> createMöglich(Boolean value) {
        return new JAXBElement<Boolean>(_Möglich_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zauberquellen")
    public JAXBElement<Boolean> createZauberquellen(Boolean value) {
        return new JAXBElement<Boolean>(_Zauberquellen_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "waffentalent")
    public JAXBElement<String> createWaffentalent(String value) {
        return new JAXBElement<String>(_Waffentalent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wm")
    public JAXBElement<String> createWm(String value) {
        return new JAXBElement<String>(_Wm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mod")
    public JAXBElement<String> createMod(String value) {
        return new JAXBElement<String>(_Mod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausvornachteile")
    public JAXBElement<BigInteger> createAusvornachteile(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ausvornachteile_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wirkung")
    public JAXBElement<String> createWirkung(String value) {
        return new JAXBElement<String>(_Wirkung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fernkampf-basis")
    public JAXBElement<Eigenschaftswerte> createFernkampfBasis(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_FernkampfBasis_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "textkurz")
    public JAXBElement<String> createTextkurz(String value) {
        return new JAXBElement<String>(_Textkurz_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "istnachteil")
    public JAXBElement<Boolean> createIstnachteil(Boolean value) {
        return new JAXBElement<Boolean>(_Istnachteil_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kosten")
    public JAXBElement<String> createKosten(String value) {
        return new JAXBElement<String>(_Kosten_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamtschutz")
    public JAXBElement<BigInteger> createGesamtschutz(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gesamtschutz_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geburtstag")
    public JAXBElement<String> createGeburtstag(String value) {
        return new JAXBElement<String>(_Geburtstag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variante")
    public JAXBElement<String> createVariante(String value) {
        return new JAXBElement<String>(_Variante_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parade")
    public JAXBElement<Eigenschaftswerte> createParade(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Parade_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mirakelminus")
    public JAXBElement<Boolean> createMirakelminus(Boolean value) {
        return new JAXBElement<Boolean>(_Mirakelminus_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gekauft")
    public JAXBElement<BigInteger> createGekauft(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gekauft_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geldkreise")
    public JAXBElement<Boolean> createGeldkreise(Boolean value) {
        return new JAXBElement<Boolean>(_Geldkreise_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "frei")
    public JAXBElement<BigInteger> createFrei(BigInteger value) {
        return new JAXBElement<BigInteger>(_Frei_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attacke")
    public JAXBElement<Eigenschaftswerte> createAttacke(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Attacke_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "istgabe")
    public JAXBElement<Boolean> createIstgabe(Boolean value) {
        return new JAXBElement<Boolean>(_Istgabe_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausweichenausweichenmod")
    public JAXBElement<BigInteger> createAusweichenausweichenmod(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ausweichenausweichenmod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wirkungsdauer")
    public JAXBElement<String> createWirkungsdauer(String value) {
        return new JAXBElement<String>(_Wirkungsdauer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beschreibung")
    public JAXBElement<String> createBeschreibung(String value) {
        return new JAXBElement<String>(_Beschreibung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "magisch")
    public JAXBElement<Boolean> createMagisch(Boolean value) {
        return new JAXBElement<Boolean>(_Magisch_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsmodell")
    public JAXBElement<String> createRsmodell(String value) {
        return new JAXBElement<String>(_Rsmodell_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswertezukaufbar503325 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lebensenergie")
    public JAXBElement<Eigenschaftswertezukaufbar503325> createLebensenergie(Eigenschaftswertezukaufbar503325 value) {
        return new JAXBElement<Eigenschaftswertezukaufbar503325>(_Lebensenergie_QNAME, Eigenschaftswertezukaufbar503325 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "metatalent")
    public JAXBElement<Boolean> createMetatalent(Boolean value) {
        return new JAXBElement<Boolean>(_Metatalent_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "charisma")
    public JAXBElement<Eigenschaftswerte> createCharisma(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Charisma_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "merkmale")
    public JAXBElement<String> createMerkmale(String value) {
        return new JAXBElement<String>(_Merkmale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stand")
    public JAXBElement<String> createStand(String value) {
        return new JAXBElement<String>(_Stand_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nameausfuehrlich")
    public JAXBElement<String> createNameausfuehrlich(String value) {
        return new JAXBElement<String>(_Nameausfuehrlich_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "heldenversion")
    public JAXBElement<BigInteger> createHeldenversion(BigInteger value) {
        return new JAXBElement<BigInteger>(_Heldenversion_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "akt")
    public JAXBElement<BigInteger> createAkt(BigInteger value) {
        return new JAXBElement<BigInteger>(_Akt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gewicht")
    public JAXBElement<BigDecimal> createGewicht(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Gewicht_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reichweite")
    public JAXBElement<String> createReichweite(String value) {
        return new JAXBElement<String>(_Reichweite_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamtwertinsilberstuecken")
    public JAXBElement<BigDecimal> createGesamtwertinsilberstuecken(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Gesamtwertinsilberstuecken_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "at")
    public JAXBElement<String> createAt(String value) {
        return new JAXBElement<String>(_At_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "metatalente")
    public JAXBElement<Boolean> createMetatalente(Boolean value) {
        return new JAXBElement<Boolean>(_Metatalente_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mut")
    public JAXBElement<Eigenschaftswerte> createMut(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Mut_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "namemitvariante")
    public JAXBElement<String> createNamemitvariante(String value) {
        return new JAXBElement<String>(_Namemitvariante_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nameausfuehrlichmitprobe")
    public JAXBElement<String> createNameausfuehrlichmitprobe(String value) {
        return new JAXBElement<String>(_Nameausfuehrlichmitprobe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intuition")
    public JAXBElement<Eigenschaftswerte> createIntuition(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Intuition_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswertezukaufbar503325 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausdauer")
    public JAXBElement<Eigenschaftswertezukaufbar503325> createAusdauer(Eigenschaftswertezukaufbar503325 value) {
        return new JAXBElement<Eigenschaftswertezukaufbar503325>(_Ausdauer_QNAME, Eigenschaftswertezukaufbar503325 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamtzonenschutz")
    public JAXBElement<BigInteger> createGesamtzonenschutz(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gesamtzonenschutz_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uhrzeit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUhrzeit(String value) {
        return new JAXBElement<String>(_Uhrzeit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswertezukaufbar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "magieresistenz")
    public JAXBElement<Eigenschaftswertezukaufbar> createMagieresistenz(Eigenschaftswertezukaufbar value) {
        return new JAXBElement<Eigenschaftswertezukaufbar>(_Magieresistenz_QNAME, Eigenschaftswertezukaufbar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "schriftmuttersprache")
    public JAXBElement<Boolean> createSchriftmuttersprache(Boolean value) {
        return new JAXBElement<Boolean>(_Schriftmuttersprache_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gewandtheit")
    public JAXBElement<Eigenschaftswerte> createGewandtheit(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Gewandtheit_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lang")
    public JAXBElement<String> createLang(String value) {
        return new JAXBElement<String>(_Lang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "grundlage")
    public JAXBElement<String> createGrundlage(String value) {
        return new JAXBElement<String>(_Grundlage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geschlecht")
    public JAXBElement<String> createGeschlecht(String value) {
        return new JAXBElement<String>(_Geschlecht_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kopf")
    public JAXBElement<BigInteger> createKopf(BigInteger value) {
        return new JAXBElement<BigInteger>(_Kopf_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bildPfad")
    public JAXBElement<String> createBildPfad(String value) {
        return new JAXBElement<String>(_BildPfad_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hauszauberformatiert")
    public JAXBElement<String> createHauszauberformatiert(String value) {
        return new JAXBElement<String>(_Hauszauberformatiert_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "brust")
    public JAXBElement<BigInteger> createBrust(BigInteger value) {
        return new JAXBElement<BigInteger>(_Brust_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "grad")
    public JAXBElement<BigInteger> createGrad(BigInteger value) {
        return new JAXBElement<BigInteger>(_Grad_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "namenaufseiten")
    public JAXBElement<Boolean> createNamenaufseiten(Boolean value) {
        return new JAXBElement<Boolean>(_Namenaufseiten_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bereich")
    public JAXBElement<String> createBereich(String value) {
        return new JAXBElement<String>(_Bereich_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "istschlechteeigenschaft")
    public JAXBElement<Boolean> createIstschlechteeigenschaft(Boolean value) {
        return new JAXBElement<Boolean>(_Istschlechteeigenschaft_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lernkomplexit\u00e4t")
    public JAXBElement<String> createLernkomplexität(String value) {
        return new JAXBElement<String>(_Lernkomplexität_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rs")
    public JAXBElement<String> createRs(String value) {
        return new JAXBElement<String>(_Rs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spalte2")
    public JAXBElement<String> createSpalte2(String value) {
        return new JAXBElement<String>(_Spalte2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "arten")
    public JAXBElement<String> createArten(String value) {
        return new JAXBElement<String>(_Arten_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rest")
    public JAXBElement<BigInteger> createRest(BigInteger value) {
        return new JAXBElement<BigInteger>(_Rest_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sprachkomplexit\u00e4t")
    public JAXBElement<BigInteger> createSprachkomplexität(BigInteger value) {
        return new JAXBElement<BigInteger>(_Sprachkomplexität_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "titel")
    public JAXBElement<String> createTitel(String value) {
        return new JAXBElement<String>(_Titel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bauch")
    public JAXBElement<BigInteger> createBauch(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bauch_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ini")
    public JAXBElement<BigInteger> createIni(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ini_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "repr\u00e4sentation")
    public JAXBElement<String> createRepräsentation(String value) {
        return new JAXBElement<String>(_Repräsentation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausweichenakrobatikmod")
    public JAXBElement<BigInteger> createAusweichenakrobatikmod(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ausweichenakrobatikmod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nummer")
    public JAXBElement<BigInteger> createNummer(BigInteger value) {
        return new JAXBElement<BigInteger>(_Nummer_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "koerperkraft")
    public JAXBElement<Eigenschaftswerte> createKoerperkraft(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Koerperkraft_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamt")
    public JAXBElement<BigInteger> createGesamt(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gesamt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kultur")
    public JAXBElement<String> createKultur(String value) {
        return new JAXBElement<String>(_Kultur_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rasse")
    public JAXBElement<String> createRasse(String value) {
        return new JAXBElement<String>(_Rasse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "so")
    public JAXBElement<BigInteger> createSo(BigInteger value) {
        return new JAXBElement<BigInteger>(_So_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "probenwerte")
    public JAXBElement<String> createProbenwerte(String value) {
        return new JAXBElement<String>(_Probenwerte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aussonderfertigkeiten")
    public JAXBElement<BigInteger> createAussonderfertigkeiten(BigInteger value) {
        return new JAXBElement<BigInteger>(_Aussonderfertigkeiten_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bezeichner")
    public JAXBElement<String> createBezeichner(String value) {
        return new JAXBElement<String>(_Bezeichner_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerteastrale }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "astralenergie")
    public JAXBElement<Eigenschaftswerteastrale> createAstralenergie(Eigenschaftswerteastrale value) {
        return new JAXBElement<Eigenschaftswerteastrale>(_Astralenergie_QNAME, Eigenschaftswerteastrale.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geweiht")
    public JAXBElement<Boolean> createGeweiht(Boolean value) {
        return new JAXBElement<Boolean>(_Geweiht_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aktinklrueckkaufbarepasp")
    public JAXBElement<BigInteger> createAktinklrueckkaufbarepasp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Aktinklrueckkaufbarepasp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "klugheit")
    public JAXBElement<Eigenschaftswerte> createKlugheit(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Klugheit_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "be")
    public JAXBElement<String> createBe(String value) {
        return new JAXBElement<String>(_Be_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "behinderung")
    public JAXBElement<String> createBehinderung(String value) {
        return new JAXBElement<String>(_Behinderung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "konstitution")
    public JAXBElement<Eigenschaftswerte> createKonstitution(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Konstitution_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bf")
    public JAXBElement<String> createBf(String value) {
        return new JAXBElement<String>(_Bf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gesamtpreis")
    public JAXBElement<BigInteger> createGesamtpreis(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gesamtpreis_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "muttersprache")
    public JAXBElement<Boolean> createMuttersprache(Boolean value) {
        return new JAXBElement<Boolean>(_Muttersprache_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bfmin")
    public JAXBElement<BigInteger> createBfmin(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bfmin_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kommentar")
    public JAXBElement<String> createKommentar(String value) {
        return new JAXBElement<String>(_Kommentar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "komplexit\u00e4t")
    public JAXBElement<String> createKomplexität(String value) {
        return new JAXBElement<String>(_Komplexität_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hauszauber")
    public JAXBElement<Boolean> createHauszauber(Boolean value) {
        return new JAXBElement<Boolean>(_Hauszauber_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswertezukaufbar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "karmaenergie")
    public JAXBElement<Eigenschaftswertezukaufbar> createKarmaenergie(Eigenschaftswertezukaufbar value) {
        return new JAXBElement<Eigenschaftswertezukaufbar>(_Karmaenergie_QNAME, Eigenschaftswertezukaufbar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Eigenschaftswerte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geschwindigkeit")
    public JAXBElement<Eigenschaftswerte> createGeschwindigkeit(Eigenschaftswerte value) {
        return new JAXBElement<Eigenschaftswerte>(_Geschwindigkeit_QNAME, Eigenschaftswerte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zweitlehrsprache")
    public JAXBElement<Boolean> createZweitlehrsprache(Boolean value) {
        return new JAXBElement<Boolean>(_Zweitlehrsprache_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wundschwelle")
    public JAXBElement<BigInteger> createWundschwelle(BigInteger value) {
        return new JAXBElement<BigInteger>(_Wundschwelle_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ausweichenmod")
    public JAXBElement<BigInteger> createAusweichenmod(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ausweichenmod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkerarm")
    public JAXBElement<BigInteger> createLinkerarm(BigInteger value) {
        return new JAXBElement<BigInteger>(_Linkerarm_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkesbein")
    public JAXBElement<BigInteger> createLinkesbein(BigInteger value) {
        return new JAXBElement<BigInteger>(_Linkesbein_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "basis")
    public JAXBElement<Boolean> createBasis(Boolean value) {
        return new JAXBElement<Boolean>(_Basis_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "akt50")
    public JAXBElement<BigInteger> createAkt50(BigInteger value) {
        return new JAXBElement<BigInteger>(_Akt50_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kaufbar")
    public JAXBElement<BigInteger> createKaufbar(BigInteger value) {
        return new JAXBElement<BigInteger>(_Kaufbar_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mirakelplus")
    public JAXBElement<Boolean> createMirakelplus(Boolean value) {
        return new JAXBElement<Boolean>(_Mirakelplus_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gilde")
    public JAXBElement<String> createGilde(String value) {
        return new JAXBElement<String>(_Gilde_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "istvorteil")
    public JAXBElement<Boolean> createIstvorteil(Boolean value) {
        return new JAXBElement<Boolean>(_Istvorteil_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anzahl")
    public JAXBElement<BigInteger> createAnzahl(BigInteger value) {
        return new JAXBElement<BigInteger>(_Anzahl_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tp")
    public JAXBElement<String> createTp(String value) {
        return new JAXBElement<String>(_Tp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wert")
    public JAXBElement<BigInteger> createWert(BigInteger value) {
        return new JAXBElement<BigInteger>(_Wert_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wertinsilberstuecken")
    public JAXBElement<BigDecimal> createWertinsilberstuecken(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Wertinsilberstuecken_QNAME, BigDecimal.class, null, value);
    }

}
