//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}nummer"/>
 *         &lt;element ref="{}getName"/>
 *         &lt;element ref="{}grundlage"/>
 *         &lt;element ref="{}be"/>
 *         &lt;element ref="{}rs"/>
 *         &lt;element ref="{}kopf"/>
 *         &lt;element ref="{}brust"/>
 *         &lt;element ref="{}ruecken"/>
 *         &lt;element ref="{}bauch"/>
 *         &lt;element ref="{}linkerarm"/>
 *         &lt;element ref="{}rechterarm"/>
 *         &lt;element ref="{}linkesbein"/>
 *         &lt;element ref="{}rechtesbein"/>
 *         &lt;element ref="{}gesamt"/>
 *         &lt;element ref="{}gesamtzonenschutz"/>
 *         &lt;element ref="{}behinderung"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nummer",
    "name",
    "grundlage",
    "be",
    "rs",
    "kopf",
    "brust",
    "ruecken",
    "bauch",
    "linkerarm",
    "rechterarm",
    "linkesbein",
    "rechtesbein",
    "gesamt",
    "gesamtzonenschutz",
    "behinderung"
})
@XmlRootElement(name = "ruestung")
public class Ruestung {

    protected BigInteger nummer;
    protected String name;
    protected String grundlage;
    protected String be;
    protected String rs;
    protected BigInteger kopf;
    protected BigInteger brust;
    protected BigInteger ruecken;
    protected BigInteger bauch;
    protected BigInteger linkerarm;
    protected BigInteger rechterarm;
    protected BigInteger linkesbein;
    protected BigInteger rechtesbein;
    protected BigInteger gesamt;
    protected BigInteger gesamtzonenschutz;
    protected String behinderung;

    /**
     * Gets the value of the nummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNummer() {
        return nummer;
    }

    /**
     * Sets the value of the nummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNummer(BigInteger value) {
        this.nummer = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the grundlage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrundlage() {
        return grundlage;
    }

    /**
     * Sets the value of the grundlage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrundlage(String value) {
        this.grundlage = value;
    }

    /**
     * Gets the value of the be property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBe() {
        return be;
    }

    /**
     * Sets the value of the be property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBe(String value) {
        this.be = value;
    }

    /**
     * Gets the value of the rs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRs() {
        return rs;
    }

    /**
     * Sets the value of the rs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRs(String value) {
        this.rs = value;
    }

    /**
     * Gets the value of the kopf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKopf() {
        return kopf;
    }

    /**
     * Sets the value of the kopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKopf(BigInteger value) {
        this.kopf = value;
    }

    /**
     * Gets the value of the brust property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrust() {
        return brust;
    }

    /**
     * Sets the value of the brust property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrust(BigInteger value) {
        this.brust = value;
    }

    /**
     * Gets the value of the ruecken property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRuecken() {
        return ruecken;
    }

    /**
     * Sets the value of the ruecken property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRuecken(BigInteger value) {
        this.ruecken = value;
    }

    /**
     * Gets the value of the bauch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBauch() {
        return bauch;
    }

    /**
     * Sets the value of the bauch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBauch(BigInteger value) {
        this.bauch = value;
    }

    /**
     * Gets the value of the linkerarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinkerarm() {
        return linkerarm;
    }

    /**
     * Sets the value of the linkerarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinkerarm(BigInteger value) {
        this.linkerarm = value;
    }

    /**
     * Gets the value of the rechterarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRechterarm() {
        return rechterarm;
    }

    /**
     * Sets the value of the rechterarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRechterarm(BigInteger value) {
        this.rechterarm = value;
    }

    /**
     * Gets the value of the linkesbein property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinkesbein() {
        return linkesbein;
    }

    /**
     * Sets the value of the linkesbein property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinkesbein(BigInteger value) {
        this.linkesbein = value;
    }

    /**
     * Gets the value of the rechtesbein property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRechtesbein() {
        return rechtesbein;
    }

    /**
     * Sets the value of the rechtesbein property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRechtesbein(BigInteger value) {
        this.rechtesbein = value;
    }

    /**
     * Gets the value of the gesamt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGesamt() {
        return gesamt;
    }

    /**
     * Sets the value of the gesamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGesamt(BigInteger value) {
        this.gesamt = value;
    }

    /**
     * Gets the value of the gesamtzonenschutz property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGesamtzonenschutz() {
        return gesamtzonenschutz;
    }

    /**
     * Sets the value of the gesamtzonenschutz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGesamtzonenschutz(BigInteger value) {
        this.gesamtzonenschutz = value;
    }

    /**
     * Gets the value of the behinderung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehinderung() {
        return behinderung;
    }

    /**
     * Sets the value of the behinderung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehinderung(String value) {
        this.behinderung = value;
    }

}
