// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import java.util.ArrayList;
import java.util.List;

public class AbenteuerDto {
	private int id;
	private String name;
	private int gruppeId;
	private String gruppe;
	private int kampagneId;
	private String kampagne;
	private boolean meister;
	private int datumValue;
	private Bonus bonusAll = new Bonus();
	private int ap;
	private List<NoteDto> notes;
	private List<HeldenBonus> bonus = new ArrayList<>();


	public AbenteuerDto() {
	}


	public int getId() {
		return this.id;
	}


	public String getName() {
		return this.name;
	}


	public int getGruppeId() {
		return this.gruppeId;
	}


	public String getGruppe() {
		return this.gruppe;
	}


	public int getKampagneId() {
		return this.kampagneId;
	}


	public String getKampagne() {
		return this.kampagne;
	}


	public boolean isMeister() {
		return this.meister;
	}


	public int getDatumValue() {
		return this.datumValue;
	}


	public Bonus getBonusAll() {
		return this.bonusAll;
	}


	public int getAp() {
		return this.ap;
	}


	public List<NoteDto> getNotes() {
		return this.notes;
	}


	public List<HeldenBonus> getBonus() {
		return this.bonus;
	}


	public void setId(final int id) {
		this.id = id;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setGruppeId(final int gruppeId) {
		this.gruppeId = gruppeId;
	}


	public void setGruppe(final String gruppe) {
		this.gruppe = gruppe;
	}


	public void setKampagneId(final int kampagneId) {
		this.kampagneId = kampagneId;
	}


	public void setKampagne(final String kampagne) {
		this.kampagne = kampagne;
	}


	public void setMeister(final boolean meister) {
		this.meister = meister;
	}


	public void setDatumValue(final int datumValue) {
		this.datumValue = datumValue;
	}


	public void setBonusAll(final Bonus bonusAll) {
		this.bonusAll = bonusAll;
	}


	public void setAp(final int ap) {
		this.ap = ap;
	}


	public void setNotes(final List<NoteDto> notes) {
		this.notes = notes;
	}


	public void setBonus(final List<HeldenBonus> bonus) {
		this.bonus = bonus;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof AbenteuerDto)) return false;
		final AbenteuerDto other = (AbenteuerDto) o;
		if (!other.canEqual((Object) this)) return false;
		if (this.getId() != other.getId()) return false;
		final Object this$name = this.getName();
		final Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		if (this.getGruppeId() != other.getGruppeId()) return false;
		final Object this$gruppe = this.getGruppe();
		final Object other$gruppe = other.getGruppe();
		if (this$gruppe == null ? other$gruppe != null : !this$gruppe.equals(other$gruppe)) return false;
		if (this.getKampagneId() != other.getKampagneId()) return false;
		final Object this$kampagne = this.getKampagne();
		final Object other$kampagne = other.getKampagne();
		if (this$kampagne == null ? other$kampagne != null : !this$kampagne.equals(other$kampagne)) return false;
		if (this.isMeister() != other.isMeister()) return false;
		if (this.getDatumValue() != other.getDatumValue()) return false;
		final Object this$bonusAll = this.getBonusAll();
		final Object other$bonusAll = other.getBonusAll();
		if (this$bonusAll == null ? other$bonusAll != null : !this$bonusAll.equals(other$bonusAll)) return false;
		if (this.getAp() != other.getAp()) return false;
		final Object this$notes = this.getNotes();
		final Object other$notes = other.getNotes();
		if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
		final Object this$bonus = this.getBonus();
		final Object other$bonus = other.getBonus();
		if (this$bonus == null ? other$bonus != null : !this$bonus.equals(other$bonus)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof AbenteuerDto;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getId();
		final Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		result = result * PRIME + this.getGruppeId();
		final Object $gruppe = this.getGruppe();
		result = result * PRIME + ($gruppe == null ? 43 : $gruppe.hashCode());
		result = result * PRIME + this.getKampagneId();
		final Object $kampagne = this.getKampagne();
		result = result * PRIME + ($kampagne == null ? 43 : $kampagne.hashCode());
		result = result * PRIME + (this.isMeister() ? 79 : 97);
		result = result * PRIME + this.getDatumValue();
		final Object $bonusAll = this.getBonusAll();
		result = result * PRIME + ($bonusAll == null ? 43 : $bonusAll.hashCode());
		result = result * PRIME + this.getAp();
		final Object $notes = this.getNotes();
		result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
		final Object $bonus = this.getBonus();
		result = result * PRIME + ($bonus == null ? 43 : $bonus.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "AbenteuerDto(id=" + this.getId() + ", name=" + this.getName() + ", gruppeId=" + this.getGruppeId() + ", gruppe=" + this.getGruppe() + ", kampagneId=" + this.getKampagneId() + ", kampagne=" + this.getKampagne() + ", meister=" + this.isMeister() + ", datumValue=" + this.getDatumValue() + ", bonusAll=" + this.getBonusAll() + ", ap=" + this.getAp() + ", notes=" + this.getNotes() + ", bonus=" + this.getBonus() + ")";
	}
}
