// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

public class BaseDto {
	private int id;


	public BaseDto(final int id) {
		this.id = id;
	}


	public int getId() {
		return this.id;
	}


	public void setId(final int id) {
		this.id = id;
	}
}
