// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

public class Bonus {
	private int ap;
	private BigInteger heldid;
	private List<String> ses = new ArrayList<>();
	private List<String> lms = new ArrayList<>();
	private List<String> notes = new ArrayList<>();


	public Bonus() {
	}


	public int getAp() {
		return this.ap;
	}


	public List<String> getSes() {
		return this.ses;
	}


	public List<String> getLms() {
		return this.lms;
	}


	public List<String> getNotes() {
		return this.notes;
	}


	public void setAp(final int ap) {
		this.ap = ap;
	}


	public void setSes(final List<String> ses) {
		this.ses = ses;
	}


	public void setLms(final List<String> lms) {
		this.lms = lms;
	}


	public void setNotes(final List<String> notes) {
		this.notes = notes;
	}

	public void setHeldid(BigInteger heldid) {
		this.heldid = heldid;
	}

	public BigInteger getHeldid() {
		return heldid;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof Bonus)) return false;
		final Bonus other = (Bonus) o;
		if (!other.canEqual((Object) this)) return false;
		if (this.getAp() != other.getAp()) return false;
		final Object this$ses = this.getSes();
		final Object other$ses = other.getSes();
		if (this$ses == null ? other$ses != null : !this$ses.equals(other$ses)) return false;
		final Object this$lms = this.getLms();
		final Object other$lms = other.getLms();
		if (this$lms == null ? other$lms != null : !this$lms.equals(other$lms)) return false;
		final Object this$notes = this.getNotes();
		final Object other$notes = other.getNotes();
		if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof Bonus;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getAp();
		final Object $ses = this.getSes();
		result = result * PRIME + ($ses == null ? 43 : $ses.hashCode());
		final Object $lms = this.getLms();
		result = result * PRIME + ($lms == null ? 43 : $lms.hashCode());
		final Object $notes = this.getNotes();
		result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "Bonus(ap=" + this.getAp() + ", ses=" + this.getSes() + ", lms=" + this.getLms() + ", notes=" + this.getNotes() + ")";
	}
}
