// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import java.math.BigInteger;

public class CreateBonus {
	private Integer id;
	private int abenteuerId;
	private BigInteger heldid;
	private Bonus bonus;


	public CreateBonus() {
	}


	public Integer getId() {
		return this.id;
	}


	public int getAbenteuerId() {
		return this.abenteuerId;
	}


	public BigInteger getHeldid() {
		return this.heldid;
	}


	public Bonus getBonus() {
		return this.bonus;
	}


	public void setId(final Integer id) {
		this.id = id;
	}


	public void setAbenteuerId(final int abenteuerId) {
		this.abenteuerId = abenteuerId;
	}


	public void setHeldid(final BigInteger heldid) {
		this.heldid = heldid;
	}


	public void setBonus(final Bonus bonus) {
		this.bonus = bonus;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof CreateBonus)) return false;
		final CreateBonus other = (CreateBonus) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$id = this.getId();
		final Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		if (this.getAbenteuerId() != other.getAbenteuerId()) return false;
		final Object this$heldid = this.getHeldid();
		final Object other$heldid = other.getHeldid();
		if (this$heldid == null ? other$heldid != null : !this$heldid.equals(other$heldid)) return false;
		final Object this$bonus = this.getBonus();
		final Object other$bonus = other.getBonus();
		if (this$bonus == null ? other$bonus != null : !this$bonus.equals(other$bonus)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof CreateBonus;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		result = result * PRIME + this.getAbenteuerId();
		final Object $heldid = this.getHeldid();
		result = result * PRIME + ($heldid == null ? 43 : $heldid.hashCode());
		final Object $bonus = this.getBonus();
		result = result * PRIME + ($bonus == null ? 43 : $bonus.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "CreateBonus(id=" + this.getId() + ", abenteuerId=" + this.getAbenteuerId() + ", heldid=" + this.getHeldid() + ", bonus=" + this.getBonus() + ")";
	}
}
