// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

public class DsaMonat {
	public static final int YEAR_LENGTH = 365;
	public static final int MONTH_LENGTH = 30;
	public static final int NAMENLOS_MONTH_LENGTH = 30;
	public static final int START_YEAR = 1000;
	public static final int NAMENLOS_MONTH = 12;
	private int jahr;
	private int monat;

	public int getDbJahr() {
		return jahr - START_YEAR;
	}

	public int getDbMonat() {
		return getDbJahr() * 13 + monat;
	}

	public int getStartTag() {
		return getDbJahr() * 365 + monat * 30;
	}

	public int getEndTag() {
		if (monat == NAMENLOS_MONTH) {
			return getDbJahr() * 365 + monat * 30 + NAMENLOS_MONTH_LENGTH - 1;
		} else {
			return getDbJahr() * 365 + monat * 30 + MONTH_LENGTH - 1;
		}
	}


	public int getJahr() {
		return this.jahr;
	}


	public int getMonat() {
		return this.monat;
	}


	public void setJahr(final int jahr) {
		this.jahr = jahr;
	}


	public void setMonat(final int monat) {
		this.monat = monat;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof DsaMonat)) return false;
		final DsaMonat other = (DsaMonat) o;
		if (!other.canEqual((Object) this)) return false;
		if (this.getJahr() != other.getJahr()) return false;
		if (this.getMonat() != other.getMonat()) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof DsaMonat;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getJahr();
		result = result * PRIME + this.getMonat();
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "DsaMonat(jahr=" + this.getJahr() + ", monat=" + this.getMonat() + ")";
	}


	public DsaMonat(final int jahr, final int monat) {
		this.jahr = jahr;
		this.monat = monat;
	}
}
