// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import de.failender.dsaonline.data.entity.EventEntity;

public class EventDto {
	private String name;
	private int date;
	private int id;
	private EventEntity.Type type;


	public String getName() {
		return this.name;
	}


	public int getDate() {
		return this.date;
	}


	public int getId() {
		return this.id;
	}


	public EventEntity.Type getType() {
		return this.type;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setDate(final int date) {
		this.date = date;
	}


	public void setId(final int id) {
		this.id = id;
	}


	public void setType(final EventEntity.Type type) {
		this.type = type;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof EventDto)) return false;
		final EventDto other = (EventDto) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$name = this.getName();
		final Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		if (this.getDate() != other.getDate()) return false;
		if (this.getId() != other.getId()) return false;
		final Object this$type = this.getType();
		final Object other$type = other.getType();
		if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof EventDto;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		result = result * PRIME + this.getDate();
		result = result * PRIME + this.getId();
		final Object $type = this.getType();
		result = result * PRIME + ($type == null ? 43 : $type.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "EventDto(name=" + this.getName() + ", date=" + this.getDate() + ", id=" + this.getId() + ", type=" + this.getType() + ")";
	}


	public EventDto(final String name, final int date, final int id, final EventEntity.Type type) {
		this.name = name;
		this.date = date;
		this.id = id;
		this.type = type;
	}
}
