// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;


public class GruppeInfo {
	private String name;
	private int id;
	private boolean isMeister;
	private boolean isUserGroup;
	private String image;


	public String getName() {
		return this.name;
	}


	public int getId() {
		return this.id;
	}


	public boolean isMeister() {
		return this.isMeister;
	}


	public boolean isUserGroup() {
		return this.isUserGroup;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setId(final int id) {
		this.id = id;
	}


	public void setMeister(final boolean isMeister) {
		this.isMeister = isMeister;
	}


	public void setUserGroup(final boolean isUserGroup) {
		this.isUserGroup = isUserGroup;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof GruppeInfo)) return false;
		final GruppeInfo other = (GruppeInfo) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$name = this.getName();
		final Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		if (this.getId() != other.getId()) return false;
		if (this.isMeister() != other.isMeister()) return false;
		if (this.isUserGroup() != other.isUserGroup()) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof GruppeInfo;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		result = result * PRIME + this.getId();
		result = result * PRIME + (this.isMeister() ? 79 : 97);
		result = result * PRIME + (this.isUserGroup() ? 79 : 97);
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "GruppeInfo(name=" + this.getName() + ", id=" + this.getId() + ", isMeister=" + this.isMeister() + ", isUserGroup=" + this.isUserGroup() + ")";
	}


	public GruppeInfo(final String name, final int id, final boolean isMeister, final boolean isUserGroup, String image) {
		this.name = name;
		this.id = id;
		this.isMeister = isMeister;
		this.isUserGroup = isUserGroup;
		this.image = image;
	}

	public String getImage() {
		return image;
	}
}
