// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import java.math.BigInteger;
import java.util.Date;

public class HeldenInfo {
	private String name;
	private Date lastChanged;
	private int version;
	private String gruppe;
	private BigInteger id;
	private boolean oeffentlich;
	private boolean active;


	public String getName() {
		return this.name;
	}


	public Date getLastChanged() {
		return this.lastChanged;
	}


	public int getVersion() {
		return this.version;
	}


	public String getGruppe() {
		return this.gruppe;
	}


	public BigInteger getId() {
		return this.id;
	}


	public boolean isOeffentlich() {
		return this.oeffentlich;
	}


	public boolean isActive() {
		return this.active;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setLastChanged(final Date lastChanged) {
		this.lastChanged = lastChanged;
	}


	public void setVersion(final int version) {
		this.version = version;
	}


	public void setGruppe(final String gruppe) {
		this.gruppe = gruppe;
	}


	public void setId(final BigInteger id) {
		this.id = id;
	}


	public void setOeffentlich(final boolean oeffentlich) {
		this.oeffentlich = oeffentlich;
	}


	public void setActive(final boolean active) {
		this.active = active;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof HeldenInfo)) return false;
		final HeldenInfo other = (HeldenInfo) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$name = this.getName();
		final Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final Object this$lastChanged = this.getLastChanged();
		final Object other$lastChanged = other.getLastChanged();
		if (this$lastChanged == null ? other$lastChanged != null : !this$lastChanged.equals(other$lastChanged)) return false;
		if (this.getVersion() != other.getVersion()) return false;
		final Object this$gruppe = this.getGruppe();
		final Object other$gruppe = other.getGruppe();
		if (this$gruppe == null ? other$gruppe != null : !this$gruppe.equals(other$gruppe)) return false;
		final Object this$id = this.getId();
		final Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		if (this.isOeffentlich() != other.isOeffentlich()) return false;
		if (this.isActive() != other.isActive()) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof HeldenInfo;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final Object $lastChanged = this.getLastChanged();
		result = result * PRIME + ($lastChanged == null ? 43 : $lastChanged.hashCode());
		result = result * PRIME + this.getVersion();
		final Object $gruppe = this.getGruppe();
		result = result * PRIME + ($gruppe == null ? 43 : $gruppe.hashCode());
		final Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		result = result * PRIME + (this.isOeffentlich() ? 79 : 97);
		result = result * PRIME + (this.isActive() ? 79 : 97);
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "HeldenInfo(name=" + this.getName() + ", lastChanged=" + this.getLastChanged() + ", version=" + this.getVersion() + ", gruppe=" + this.getGruppe() + ", id=" + this.getId() + ", oeffentlich=" + this.isOeffentlich() + ", active=" + this.isActive() + ")";
	}


	public HeldenInfo(final String name, final Date lastChanged, final int version, final String gruppe, final BigInteger id, final boolean oeffentlich, final boolean active) {
		this.name = name;
		this.lastChanged = lastChanged;
		this.version = version;
		this.gruppe = gruppe;
		this.id = id;
		this.oeffentlich = oeffentlich;
		this.active = active;
	}
}
