// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

import java.util.Date;

public class HeldVersion {
	private String letztesAbenteuer;
	private Date datum;
	private int version;


	public String getLetztesAbenteuer() {
		return this.letztesAbenteuer;
	}


	public Date getDatum() {
		return this.datum;
	}


	public int getVersion() {
		return this.version;
	}


	public void setLetztesAbenteuer(final String letztesAbenteuer) {
		this.letztesAbenteuer = letztesAbenteuer;
	}


	public void setDatum(final Date datum) {
		this.datum = datum;
	}


	public void setVersion(final int version) {
		this.version = version;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof HeldVersion)) return false;
		final HeldVersion other = (HeldVersion) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$letztesAbenteuer = this.getLetztesAbenteuer();
		final Object other$letztesAbenteuer = other.getLetztesAbenteuer();
		if (this$letztesAbenteuer == null ? other$letztesAbenteuer != null : !this$letztesAbenteuer.equals(other$letztesAbenteuer)) return false;
		final Object this$datum = this.getDatum();
		final Object other$datum = other.getDatum();
		if (this$datum == null ? other$datum != null : !this$datum.equals(other$datum)) return false;
		if (this.getVersion() != other.getVersion()) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof HeldVersion;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $letztesAbenteuer = this.getLetztesAbenteuer();
		result = result * PRIME + ($letztesAbenteuer == null ? 43 : $letztesAbenteuer.hashCode());
		final Object $datum = this.getDatum();
		result = result * PRIME + ($datum == null ? 43 : $datum.hashCode());
		result = result * PRIME + this.getVersion();
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "HeldVersion(letztesAbenteuer=" + this.getLetztesAbenteuer() + ", datum=" + this.getDatum() + ", version=" + this.getVersion() + ")";
	}


	public HeldVersion(final String letztesAbenteuer, final Date datum, final int version) {
		this.letztesAbenteuer = letztesAbenteuer;
		this.datum = datum;
		this.version = version;
	}
}
