// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

public class StatisticEntry {
	private String key;
	private Object value;


	public String getKey() {
		return this.key;
	}


	public Object getValue() {
		return this.value;
	}


	public void setKey(final String key) {
		this.key = key;
	}


	public void setValue(final Object value) {
		this.value = value;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof StatisticEntry)) return false;
		final StatisticEntry other = (StatisticEntry) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$key = this.getKey();
		final Object other$key = other.getKey();
		if (this$key == null ? other$key != null : !this$key.equals(other$key)) return false;
		final Object this$value = this.getValue();
		final Object other$value = other.getValue();
		if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof StatisticEntry;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $key = this.getKey();
		result = result * PRIME + ($key == null ? 43 : $key.hashCode());
		final Object $value = this.getValue();
		result = result * PRIME + ($value == null ? 43 : $value.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "StatisticEntry(key=" + this.getKey() + ", value=" + this.getValue() + ")";
	}


	public StatisticEntry(final String key, final Object value) {
		this.key = key;
		this.value = value;
	}
}
