// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

public class UserDto extends BaseDto {
	public UserDto(int id, String name, String gruppe) {
		super(id);
		this.name = name;
		this.gruppe = gruppe;
	}

	private String name;
	private String gruppe;

	public UserDto(int id) {
		super(id);
	}


	public String getName() {
		return this.name;
	}


	public String getGruppe() {
		return this.gruppe;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setGruppe(final String gruppe) {
		this.gruppe = gruppe;
	}
}
