// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.security;

public class RestAuthentication {
	private String password;
	private String username;


	public String getPassword() {
		return this.password;
	}


	public String getUsername() {
		return this.username;
	}


	public void setPassword(final String password) {
		this.password = password;
	}


	public void setUsername(final String username) {
		this.username = username;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof RestAuthentication)) return false;
		final RestAuthentication other = (RestAuthentication) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$password = this.getPassword();
		final Object other$password = other.getPassword();
		if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
		final Object this$username = this.getUsername();
		final Object other$username = other.getUsername();
		if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof RestAuthentication;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $password = this.getPassword();
		result = result * PRIME + ($password == null ? 43 : $password.hashCode());
		final Object $username = this.getUsername();
		result = result * PRIME + ($username == null ? 43 : $username.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "RestAuthentication(password=" + this.getPassword() + ", username=" + this.getUsername() + ")";
	}


	public RestAuthentication(final String password, final String username) {
		this.password = password;
		this.username = username;
	}


	public RestAuthentication() {
	}
}
