//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}augenfarbe"/>
 *         &lt;element ref="{}geburtstag"/>
 *         &lt;element ref="{}alter"/>
 *         &lt;element ref="{}geschlecht"/>
 *         &lt;element ref="{}groesse"/>
 *         &lt;element ref="{}gewicht"/>
 *         &lt;element ref="{}haarfarbe"/>
 *         &lt;element ref="{}stand"/>
 *         &lt;element ref="{}titel"/>
 *         &lt;element ref="{}getName"/>
 *         &lt;element ref="{}bildPfad"/>
 *         &lt;element ref="{}aussehen"/>
 *         &lt;element ref="{}familie"/>
 *         &lt;element ref="{}notizen"/>
 *         &lt;element ref="{}profession"/>
 *         &lt;element ref="{}ap"/>
 *         &lt;element ref="{}gp"/>
 *         &lt;element ref="{}stufe40"/>
 *         &lt;element ref="{}stufe41"/>
 *         &lt;element ref="{}gilde"/>
 *         &lt;element ref="{}magisch"/>
 *         &lt;element ref="{}geweiht"/>
 *         &lt;element ref="{}rasse"/>
 *         &lt;element ref="{}kultur"/>
 *         &lt;element ref="{}aspregeneration"/>
 *         &lt;element ref="{}leregeneration"/>
 *         &lt;element ref="{}heldenversion"/>
 *         &lt;element ref="{}wundschwelle"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "augenfarbe",
    "geburtstag",
    "alter",
    "geschlecht",
    "groesse",
    "gewicht",
    "haarfarbe",
    "stand",
    "titel",
    "name",
    "bildPfad",
    "aussehen",
    "familie",
    "notizen",
    "profession",
    "ap",
    "gp",
    "stufe40",
    "stufe41",
    "gilde",
    "magisch",
    "geweiht",
    "rasse",
    "kultur",
    "aspregeneration",
    "leregeneration",
    "heldenversion",
    "wundschwelle"
})
@XmlRootElement(name = "angaben")
public class Angaben {

    @XmlElement(required = true)
    protected String augenfarbe;
    @XmlElement(required = true)
    protected String geburtstag;
    @XmlElement(required = true)
    protected BigInteger alter;
    @XmlElement(required = true)
    protected String geschlecht;
    @XmlElement(required = true)
    protected BigInteger groesse;
    @XmlElement(required = true)
    protected BigDecimal gewicht;
    @XmlElement(required = true)
    protected String haarfarbe;
    @XmlElement(required = true)
    protected String stand;
    @XmlElement(required = true)
    protected String titel;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String bildPfad;
    @XmlElement(required = true)
    protected Aussehen aussehen;
    @XmlElement(required = true)
    protected Familie familie;
    @XmlElement(required = true)
    protected Notizen notizen;
    @XmlElement(required = true)
    protected Profession profession;
    @XmlElement(required = true)
    protected Ap ap;
    @XmlElement(required = true)
    protected Gp gp;
    @XmlElement(required = true)
    protected Stufe40 stufe40;
    @XmlElement(required = true)
    protected Stufe41 stufe41;
    @XmlElement(required = true)
    protected String gilde;
    protected boolean magisch;
    protected boolean geweiht;
    @XmlElement(required = true)
    protected String rasse;
    @XmlElement(required = true)
    protected String kultur;
    @XmlElement(required = true)
    protected String aspregeneration;
    @XmlElement(required = true)
    protected String leregeneration;
    @XmlElement(required = true)
    protected BigInteger heldenversion;
    @XmlElement(required = true)
    protected BigInteger wundschwelle;

    /**
     * Gets the value of the augenfarbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugenfarbe() {
        return augenfarbe;
    }

    /**
     * Sets the value of the augenfarbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugenfarbe(String value) {
        this.augenfarbe = value;
    }

    /**
     * Gets the value of the geburtstag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtstag() {
        return geburtstag;
    }

    /**
     * Sets the value of the geburtstag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtstag(String value) {
        this.geburtstag = value;
    }

    /**
     * Gets the value of the alter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAlter() {
        return alter;
    }

    /**
     * Sets the value of the alter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAlter(BigInteger value) {
        this.alter = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeschlecht(String value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the groesse property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGroesse() {
        return groesse;
    }

    /**
     * Sets the value of the groesse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGroesse(BigInteger value) {
        this.groesse = value;
    }

    /**
     * Gets the value of the gewicht property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGewicht() {
        return gewicht;
    }

    /**
     * Sets the value of the gewicht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGewicht(BigDecimal value) {
        this.gewicht = value;
    }

    /**
     * Gets the value of the haarfarbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaarfarbe() {
        return haarfarbe;
    }

    /**
     * Sets the value of the haarfarbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaarfarbe(String value) {
        this.haarfarbe = value;
    }

    /**
     * Gets the value of the stand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStand() {
        return stand;
    }

    /**
     * Sets the value of the stand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStand(String value) {
        this.stand = value;
    }

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bildPfad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBildPfad() {
        return bildPfad;
    }

    /**
     * Sets the value of the bildPfad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBildPfad(String value) {
        this.bildPfad = value;
    }

    /**
     * Gets the value of the aussehen property.
     * 
     * @return
     *     possible object is
     *     {@link Aussehen }
     *     
     */
    public Aussehen getAussehen() {
        return aussehen;
    }

    /**
     * Sets the value of the aussehen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aussehen }
     *     
     */
    public void setAussehen(Aussehen value) {
        this.aussehen = value;
    }

    /**
     * Gets the value of the familie property.
     * 
     * @return
     *     possible object is
     *     {@link Familie }
     *     
     */
    public Familie getFamilie() {
        return familie;
    }

    /**
     * Sets the value of the familie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Familie }
     *     
     */
    public void setFamilie(Familie value) {
        this.familie = value;
    }

    /**
     * Gets the value of the notizen property.
     * 
     * @return
     *     possible object is
     *     {@link Notizen }
     *     
     */
    public Notizen getNotizen() {
        return notizen;
    }

    /**
     * Sets the value of the notizen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notizen }
     *     
     */
    public void setNotizen(Notizen value) {
        this.notizen = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link Profession }
     *     
     */
    public Profession getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profession }
     *     
     */
    public void setProfession(Profession value) {
        this.profession = value;
    }

    /**
     * Gets the value of the ap property.
     * 
     * @return
     *     possible object is
     *     {@link Ap }
     *     
     */
    public Ap getAp() {
        return ap;
    }

    /**
     * Sets the value of the ap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ap }
     *     
     */
    public void setAp(Ap value) {
        this.ap = value;
    }

    /**
     * Gets the value of the gp property.
     * 
     * @return
     *     possible object is
     *     {@link Gp }
     *     
     */
    public Gp getGp() {
        return gp;
    }

    /**
     * Sets the value of the gp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gp }
     *     
     */
    public void setGp(Gp value) {
        this.gp = value;
    }

    /**
     * Gets the value of the stufe40 property.
     * 
     * @return
     *     possible object is
     *     {@link Stufe40 }
     *     
     */
    public Stufe40 getStufe40() {
        return stufe40;
    }

    /**
     * Sets the value of the stufe40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stufe40 }
     *     
     */
    public void setStufe40(Stufe40 value) {
        this.stufe40 = value;
    }

    /**
     * Gets the value of the stufe41 property.
     * 
     * @return
     *     possible object is
     *     {@link Stufe41 }
     *     
     */
    public Stufe41 getStufe41() {
        return stufe41;
    }

    /**
     * Sets the value of the stufe41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stufe41 }
     *     
     */
    public void setStufe41(Stufe41 value) {
        this.stufe41 = value;
    }

    /**
     * Gets the value of the gilde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGilde() {
        return gilde;
    }

    /**
     * Sets the value of the gilde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGilde(String value) {
        this.gilde = value;
    }

    /**
     * Gets the value of the magisch property.
     * 
     */
    public boolean isMagisch() {
        return magisch;
    }

    /**
     * Sets the value of the magisch property.
     * 
     */
    public void setMagisch(boolean value) {
        this.magisch = value;
    }

    /**
     * Gets the value of the geweiht property.
     * 
     */
    public boolean isGeweiht() {
        return geweiht;
    }

    /**
     * Sets the value of the geweiht property.
     * 
     */
    public void setGeweiht(boolean value) {
        this.geweiht = value;
    }

    /**
     * Gets the value of the rasse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRasse() {
        return rasse;
    }

    /**
     * Sets the value of the rasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRasse(String value) {
        this.rasse = value;
    }

    /**
     * Gets the value of the kultur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKultur() {
        return kultur;
    }

    /**
     * Sets the value of the kultur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKultur(String value) {
        this.kultur = value;
    }

    /**
     * Gets the value of the aspregeneration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAspregeneration() {
        return aspregeneration;
    }

    /**
     * Sets the value of the aspregeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAspregeneration(String value) {
        this.aspregeneration = value;
    }

    /**
     * Gets the value of the leregeneration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeregeneration() {
        return leregeneration;
    }

    /**
     * Sets the value of the leregeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeregeneration(String value) {
        this.leregeneration = value;
    }

    /**
     * Gets the value of the heldenversion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeldenversion() {
        return heldenversion;
    }

    /**
     * Sets the value of the heldenversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeldenversion(BigInteger value) {
        this.heldenversion = value;
    }

    /**
     * Gets the value of the wundschwelle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWundschwelle() {
        return wundschwelle;
    }

    /**
     * Sets the value of the wundschwelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWundschwelle(BigInteger value) {
        this.wundschwelle = value;
    }

    @Override
    public String toString() {
        return "Angaben{" +
                "augenfarbe='" + augenfarbe + '\'' +
                ", geburtstag='" + geburtstag + '\'' +
                ", alter=" + alter +
                ", geschlecht='" + geschlecht + '\'' +
                ", groesse=" + groesse +
                ", gewicht=" + gewicht +
                ", haarfarbe='" + haarfarbe + '\'' +
                ", stand='" + stand + '\'' +
                ", titel='" + titel + '\'' +
                ", name='" + name + '\'' +
                ", bildPfad='" + bildPfad + '\'' +
                ", aussehen=" + aussehen +
                ", familie=" + familie +
                ", notizen=" + notizen +
                ", profession=" + profession +
                ", ap=" + ap +
                ", gp=" + gp +
                ", stufe40=" + stufe40 +
                ", stufe41=" + stufe41 +
                ", gilde='" + gilde + '\'' +
                ", magisch=" + magisch +
                ", geweiht=" + geweiht +
                ", rasse='" + rasse + '\'' +
                ", kultur='" + kultur + '\'' +
                ", aspregeneration='" + aspregeneration + '\'' +
                ", leregeneration='" + leregeneration + '\'' +
                ", heldenversion=" + heldenversion +
                ", wundschwelle=" + wundschwelle +
                '}';
    }
}
