//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for eigenschaftswertezukaufbar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType getName="eigenschaftswertezukaufbar">
 *   &lt;complexContent>
 *     &lt;extension base="{}eigenschaftswerte">
 *       &lt;sequence>
 *         &lt;element ref="{}kaufbar"/>
 *         &lt;element ref="{}gekauft"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eigenschaftswertezukaufbar", propOrder = {
    "kaufbar",
    "gekauft"
})
@XmlSeeAlso({
    Eigenschaftswerteastrale.class,
    Eigenschaftswertezukaufbar503325 .class
})
public class Eigenschaftswertezukaufbar
    extends Eigenschaftswerte
{

    @XmlElement(required = true)
    protected BigInteger kaufbar;
    @XmlElement(required = true)
    protected BigInteger gekauft;

    /**
     * Gets the value of the kaufbar property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKaufbar() {
        return kaufbar;
    }

    /**
     * Sets the value of the kaufbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKaufbar(BigInteger value) {
        this.kaufbar = value;
    }

    /**
     * Gets the value of the gekauft property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGekauft() {
        return gekauft;
    }

    /**
     * Sets the value of the gekauft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGekauft(BigInteger value) {
        this.gekauft = value;
    }

}
