//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}n0"/>
 *         &lt;element ref="{}n1"/>
 *         &lt;element ref="{}n2"/>
 *         &lt;element ref="{}n3"/>
 *         &lt;element ref="{}n4"/>
 *         &lt;element ref="{}n5"/>
 *         &lt;element ref="{}n6"/>
 *         &lt;element ref="{}n7"/>
 *         &lt;element ref="{}n8"/>
 *         &lt;element ref="{}n9"/>
 *         &lt;element ref="{}n10"/>
 *         &lt;element ref="{}n11"/>
 *         &lt;element ref="{}text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "n0",
    "n1",
    "n2",
    "n3",
    "n4",
    "n5",
    "n6",
    "n7",
    "n8",
    "n9",
    "n10",
    "n11",
    "text"
})
@XmlRootElement(name = "notizen")
public class Notizen {

    @XmlElement(required = true)
    protected String n0;
    @XmlElement(required = true)
    protected String n1;
    @XmlElement(required = true)
    protected String n2;
    @XmlElement(required = true)
    protected String n3;
    @XmlElement(required = true)
    protected String n4;
    @XmlElement(required = true)
    protected String n5;
    @XmlElement(required = true)
    protected String n6;
    @XmlElement(required = true)
    protected String n7;
    @XmlElement(required = true)
    protected String n8;
    @XmlElement(required = true)
    protected String n9;
    @XmlElement(required = true)
    protected String n10;
    @XmlElement(required = true)
    protected String n11;
    @XmlElement(required = true)
    protected String text;

    /**
     * Gets the value of the n0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN0() {
        return n0;
    }

    /**
     * Sets the value of the n0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN0(String value) {
        this.n0 = value;
    }

    /**
     * Gets the value of the n1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN1() {
        return n1;
    }

    /**
     * Sets the value of the n1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN1(String value) {
        this.n1 = value;
    }

    /**
     * Gets the value of the n2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN2() {
        return n2;
    }

    /**
     * Sets the value of the n2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN2(String value) {
        this.n2 = value;
    }

    /**
     * Gets the value of the n3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN3() {
        return n3;
    }

    /**
     * Sets the value of the n3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN3(String value) {
        this.n3 = value;
    }

    /**
     * Gets the value of the n4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN4() {
        return n4;
    }

    /**
     * Sets the value of the n4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN4(String value) {
        this.n4 = value;
    }

    /**
     * Gets the value of the n5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN5() {
        return n5;
    }

    /**
     * Sets the value of the n5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN5(String value) {
        this.n5 = value;
    }

    /**
     * Gets the value of the n6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN6() {
        return n6;
    }

    /**
     * Sets the value of the n6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN6(String value) {
        this.n6 = value;
    }

    /**
     * Gets the value of the n7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN7() {
        return n7;
    }

    /**
     * Sets the value of the n7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN7(String value) {
        this.n7 = value;
    }

    /**
     * Gets the value of the n8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN8() {
        return n8;
    }

    /**
     * Sets the value of the n8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN8(String value) {
        this.n8 = value;
    }

    /**
     * Gets the value of the n9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN9() {
        return n9;
    }

    /**
     * Sets the value of the n9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN9(String value) {
        this.n9 = value;
    }

    /**
     * Gets the value of the n10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN10() {
        return n10;
    }

    /**
     * Sets the value of the n10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN10(String value) {
        this.n10 = value;
    }

    /**
     * Gets the value of the n11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN11() {
        return n11;
    }

    /**
     * Sets the value of the n11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN11(String value) {
        this.n11 = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
