//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nameausfuehrlich"/>
 *         &lt;element ref="{}getName"/>
 *         &lt;element ref="{}bezeichner"/>
 *         &lt;element ref="{}wirkung"/>
 *         &lt;element ref="{}dauer"/>
 *         &lt;element ref="{}kosten"/>
 *         &lt;element ref="{}probe"/>
 *         &lt;element getName="auswahlen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element getName="auswahl" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}getName"/>
 *                             &lt;element ref="{}feld" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}kommentar"/>
 *         &lt;element ref="{}namemitkommentar"/>
 *         &lt;element ref="{}bereich" maxOccurs="unbounded"/>
 *         &lt;element ref="{}grad" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameausfuehrlich",
    "name",
    "bezeichner",
    "wirkung",
    "dauer",
    "kosten",
    "probe",
    "auswahlen",
    "kommentar",
    "namemitkommentar",
    "bereich",
    "grad"
})
@XmlRootElement(name = "sonderfertigkeit")
public class Sonderfertigkeit {

    @XmlElement(required = true)
    protected String nameausfuehrlich;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String bezeichner;
    @XmlElement(required = true)
    protected String wirkung;
    @XmlElement(required = true)
    protected String dauer;
    @XmlElement(required = true)
    protected String kosten;
    @XmlElement(required = true)
    protected String probe;
    protected Sonderfertigkeit.Auswahlen auswahlen;
    @XmlElement(required = true)
    protected String kommentar;
    @XmlElement(required = true)
    protected String namemitkommentar;
    @XmlElement(required = true)
    protected List<String> bereich;
    protected BigInteger grad;

    /**
     * Gets the value of the nameausfuehrlich property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameausfuehrlich() {
        return nameausfuehrlich;
    }

    /**
     * Sets the value of the nameausfuehrlich property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameausfuehrlich(String value) {
        this.nameausfuehrlich = value;
    }

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bezeichner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichner() {
        return bezeichner;
    }

    /**
     * Sets the value of the bezeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichner(String value) {
        this.bezeichner = value;
    }

    /**
     * Gets the value of the wirkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWirkung() {
        return wirkung;
    }

    /**
     * Sets the value of the wirkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWirkung(String value) {
        this.wirkung = value;
    }

    /**
     * Gets the value of the dauer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDauer() {
        return dauer;
    }

    /**
     * Sets the value of the dauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDauer(String value) {
        this.dauer = value;
    }

    /**
     * Gets the value of the kosten property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKosten() {
        return kosten;
    }

    /**
     * Sets the value of the kosten property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKosten(String value) {
        this.kosten = value;
    }

    /**
     * Gets the value of the probe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbe() {
        return probe;
    }

    /**
     * Sets the value of the probe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbe(String value) {
        this.probe = value;
    }

    /**
     * Gets the value of the auswahlen property.
     * 
     * @return
     *     possible object is
     *     {@link Sonderfertigkeit.Auswahlen }
     *     
     */
    public Sonderfertigkeit.Auswahlen getAuswahlen() {
        return auswahlen;
    }

    /**
     * Sets the value of the auswahlen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sonderfertigkeit.Auswahlen }
     *     
     */
    public void setAuswahlen(Sonderfertigkeit.Auswahlen value) {
        this.auswahlen = value;
    }

    /**
     * Gets the value of the kommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKommentar() {
        return kommentar;
    }

    /**
     * Sets the value of the kommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKommentar(String value) {
        this.kommentar = value;
    }

    /**
     * Gets the value of the namemitkommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamemitkommentar() {
        return namemitkommentar;
    }

    /**
     * Sets the value of the namemitkommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamemitkommentar(String value) {
        this.namemitkommentar = value;
    }

    /**
     * Gets the value of the bereich property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bereich property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBereich().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBereich() {
        if (bereich == null) {
            bereich = new ArrayList<String>();
        }
        return this.bereich;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrad(BigInteger value) {
        this.grad = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element getName="auswahl" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}getName"/>
     *                   &lt;element ref="{}feld" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auswahl"
    })
    public static class Auswahlen {

        protected List<Sonderfertigkeit.Auswahlen.Auswahl> auswahl;

        /**
         * Gets the value of the auswahl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the auswahl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuswahl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sonderfertigkeit.Auswahlen.Auswahl }
         * 
         * 
         */
        public List<Sonderfertigkeit.Auswahlen.Auswahl> getAuswahl() {
            if (auswahl == null) {
                auswahl = new ArrayList<Sonderfertigkeit.Auswahlen.Auswahl>();
            }
            return this.auswahl;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}getName"/>
         *         &lt;element ref="{}feld" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "feld"
        })
        public static class Auswahl {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected List<Feld> feld;

            /**
             * Gets the value of the getName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the getName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the feld property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the feld property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFeld().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Feld }
             * 
             * 
             */
            public List<Feld> getFeld() {
                if (feld == null) {
                    feld = new ArrayList<Feld>();
                }
                return this.feld;
            }

        }

    }

}
