// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;


import java.math.BigInteger;

public class HeldenBonus {
	private final String name;
	private Bonus bonus = new Bonus();


	public HeldenBonus(final String name, BigInteger id) {
		this.name = name;
		bonus.setHeldid(id);
	}


	public String getName() {
		return this.name;
	}


	public Bonus getBonus() {
		return this.bonus;
	}
}
