// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.dto;

public class VersionsDTO {
	private String frontend;
	private String backend;


	public String getFrontend() {
		return this.frontend;
	}


	public String getBackend() {
		return this.backend;
	}


	public void setFrontend(final String frontend) {
		this.frontend = frontend;
	}


	public void setBackend(final String backend) {
		this.backend = backend;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof VersionsDTO)) return false;
		final VersionsDTO other = (VersionsDTO) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$frontend = this.getFrontend();
		final Object other$frontend = other.getFrontend();
		if (this$frontend == null ? other$frontend != null : !this$frontend.equals(other$frontend)) return false;
		final Object this$backend = this.getBackend();
		final Object other$backend = other.getBackend();
		if (this$backend == null ? other$backend != null : !this$backend.equals(other$backend)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof VersionsDTO;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $frontend = this.getFrontend();
		result = result * PRIME + ($frontend == null ? 43 : $frontend.hashCode());
		final Object $backend = this.getBackend();
		result = result * PRIME + ($backend == null ? 43 : $backend.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "VersionsDTO(frontend=" + this.getFrontend() + ", backend=" + this.getBackend() + ")";
	}


	public VersionsDTO(final String frontend, final String backend) {
		this.frontend = frontend;
		this.backend = backend;
	}
}
