// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.scripting.helper;

public class MethodParameter {
	private String name;
	private Class type;
	private String description;


	public String getName() {
		return this.name;
	}


	public Class getType() {
		return this.type;
	}


	public String getDescription() {
		return this.description;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setType(final Class type) {
		this.type = type;
	}


	public void setDescription(final String description) {
		this.description = description;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof MethodParameter)) return false;
		final MethodParameter other = (MethodParameter) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$name = this.getName();
		final Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final Object this$type = this.getType();
		final Object other$type = other.getType();
		if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
		final Object this$description = this.getDescription();
		final Object other$description = other.getDescription();
		if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof MethodParameter;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final Object $type = this.getType();
		result = result * PRIME + ($type == null ? 43 : $type.hashCode());
		final Object $description = this.getDescription();
		result = result * PRIME + ($description == null ? 43 : $description.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "MethodParameter(name=" + this.getName() + ", type=" + this.getType() + ", description=" + this.getDescription() + ")";
	}


	public MethodParameter(final String name, final Class type, final String description) {
		this.name = name;
		this.type = type;
		this.description = description;
	}
}
