CREATE TABLE USERS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	PASSWORD varchar(60),
	TOKEN varchar(64),
	GRUPPE_ID INTEGER NOT NULL,
	CREATED_DATE DATETIME  NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE HELDEN(
  ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  NAME MEDIUMTEXT NOT NULL,
  GRUPPE_ID INTEGER NOT NULL,
  PUBLIC TINYINT NOT NULL,
  DELETED TINYINT NOT NULL,
  ACTIVE TINYINT NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE HELD_VERSION(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  HELDID BIGINT NOT NULL,
  VERSION INTEGER NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  LAST_EVENT MEDIUMTEXT,
  AP INTEGER NOT NULL,
  PRIMARY KEY(ID),
);

ALTER TABLE HELD_VERSION ADD CONSTRAINT HELDID_VERSION UNIQUE (HELDID, VERSION);


CREATE TABLE GRUPPEN(
  ID INTEGER NOT NULL,
  NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);

INSERT INTO GRUPPEN VALUES(1, 'Der Runde Tisch');
INSERT INTO GRUPPEN VALUES(2, 'TestGruppe');
INSERT INTO GRUPPEN VALUES(3, 'Schlacht um Hamburg-Mitte');

INSERT INTO USERS VALUES(1, 'Admin', null, null,1, NOW());

CREATE TABLE ROLES(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE RIGHTS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ROLES_TO_RIGHTS(
	ROLE_ID INTEGER NOT NULL,
	RIGHT_ID INTEGER NOT NULL,
	PRIMARY KEY(ROLE_ID , RIGHT_ID)
);

CREATE TABLE ROLES_TO_USER(
	ROLE_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE TABLE USER_TO_MEISTER(
  USER_ID INTEGER NOT NULL,
  GRUPPE_ID INTEGER NOT NULL,
  PRIMARY KEY (USER_ID, GRUPPE_ID)
);

INSERT INTO ROLES VALUES
	(1, 'Administrator');


INSERT INTO RIGHTS VALUES
	(1, 'CREATE_USER'),
	(2, 'VIEW_ALL'),
	(3, 'EDIT_RIGHTS'),
	(4, 'EDIT_ALL'),
	(5, 'MEISTER');

INSERT INTO ROLES_TO_USER VALUES
  (1, 1);

INSERT INTO ROLES_TO_RIGHTS VALUES
	(1, 1),
	(1, 2),
	(1, 3),
	(1, 4),
	(1, 5);

