CREATE TABLE USERS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	PASSWORD varchar(60),
	TOKEN varchar(64) NOT NULL,
	GRUPPE_ID INTEGER NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE HELDEN(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  NAME MEDIUMTEXT NOT NULL,
  ACTIVE TINYINT NOT NULL,
  VERSION INTEGER NOT NULL,
  XML TEXT NOT NULL,
  GRUPPE_ID INTEGER NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE GRUPPEN(
  ID INTEGER NOT NULL,
  NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY(ID)
);

INSERT INTO GRUPPEN VALUES(1, 'Der Runde Tisch');
INSERT INTO GRUPPEN VALUES(2, 'TestGruppe');

INSERT INTO USERS VALUES(1, 'Failender', null, 'cead7ff39138dfb94171f19d8b46a487a4f1f53ad120ce819d6c0d86787b8c65',1, CURRENT_TIMESTAMP());




CREATE TABLE ROLES(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE RIGHTS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ROLES_TO_RIGHTS(
	ROLE_ID INTEGER NOT NULL,
	RIGHT_ID INTEGER NOT NULL,
	PRIMARY KEY(ROLE_ID , RIGHT_ID)
);

CREATE TABLE ROLES_TO_USER(
	ROLE_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	PRIMARY KEY(USER_ID, ROLE_ID)
);


INSERT INTO ROLES VALUES
	(1, 'Administrator'),
	(2, 'Meister');

INSERT INTO RIGHTS VALUES
	(1, 'CREATE_USER'),
	(2, 'VIEW_ALL');

INSERT INTO ROLES_TO_USER VALUES
  (1, 1);

INSERT INTO ROLES_TO_RIGHTS VALUES
	(1, 1),
	(1, 2),
	(2, 2);