CREATE TABLE EVENTS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	OWNER_ID INTEGER NOT NULL,
	TYPE MEDIUMINT NOT NULL,
  START_DATE INTEGER NOT NULL,
  END_DATE INTEGER,
  START_MONAT INTEGER NOT NULL,
  END_MONAT INTEGER,
	PRIMARY KEY(ID)
);


INSERT INTO EVENTS VALUES (1, 'TestEvent-20-22', 36222, 2, 20,22, 0, null);
INSERT INTO EVENTS VALUES (2, 'TestEvent-10', 36222, 2, 10,10, 0, null);
INSERT INTO EVENTS VALUES (3, 'TestEvent-35', 36222, 2, 35,35, 1, null);