CREATE TABLE EVENTS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	OWNER_ID INTEGER NOT NULL,
	TYPE MEDIUMINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE EVENT_TO_DATE(
  EVENT_ID INTEGER NOT NULL,
  DATE INTEGER NOT NULL,
  PRIMARY KEY(EVENT_ID, DATE)
)
