CREATE TABLE EVENTS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	OWNER_ID INTEGER NOT NULL,
	TYPE MEDIUMINT NOT NULL,
	DATE INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO EVENTS VALUES(1, 'Test', 1, 0, 5566 )
