CREATE TABLE ABENTEUER(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
  CREATED_DATE DATETIME  NOT NULL,
	GRUPPE_ID INTEGER NOT NULL,
  AP INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ABENTEUER_BONUS_AP(
  ID INTEGER NOT NULL AUTO_INCREMENT,
	HELD BIGINTEGER NOT NULL,
	ABENTEUER_ID INTEGER NOT NULL,
  AP INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ABENTEUER_SES(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	HELD BIGINTEGER NOT NULL,
	ABENTEUER_ID INTEGER NOT NULL,
	SE VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID)
);