CREATE TABLE KAMPAGNEN(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME varchar(40) NOT NULL,
	GRUPPE_ID INTEGER NOT NULL,
	CREATED_DATE DATETIME NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO RIGHTS VALUES
	(9, 'EDIT_KAMPAGNE');

INSERT INTO ROLES_TO_RIGHTS VALUES
	(1, 9);

TRUNCATE TABLE ABENTEUER;

ALTER TABLE ABENTEUER
	ADD COLUMN KAMPAGNE INTEGER NOT NULL;