CREATE TABLE ABENTEUER_LM(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	HELD INTEGER NOT NULL,
	ABENTEUER_ID INTEGER,
	LM VARCHAR(200) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ABENTEUER_NOTES(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	HELD INTEGER NOT NULL,
	ABENTEUER_ID INTEGER,
	NOTE MEDIUMTEXT NOT NULL,
	PRIMARY KEY(ID)
);