// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.scripting;

public class ScriptLog {
	private String level;
	private String value;


	public String getLevel() {
		return this.level;
	}


	public String getValue() {
		return this.value;
	}


	public void setLevel(final String level) {
		this.level = level;
	}


	public void setValue(final String value) {
		this.value = value;
	}

	@Override

	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof ScriptLog)) return false;
		final ScriptLog other = (ScriptLog) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$level = this.getLevel();
		final Object other$level = other.getLevel();
		if (this$level == null ? other$level != null : !this$level.equals(other$level)) return false;
		final Object this$value = this.getValue();
		final Object other$value = other.getValue();
		if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
		return true;
	}


	protected boolean canEqual(final Object other) {
		return other instanceof ScriptLog;
	}

	@Override

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $level = this.getLevel();
		result = result * PRIME + ($level == null ? 43 : $level.hashCode());
		final Object $value = this.getValue();
		result = result * PRIME + ($value == null ? 43 : $value.hashCode());
		return result;
	}

	@Override

	public java.lang.String toString() {
		return "ScriptLog(level=" + this.getLevel() + ", value=" + this.getValue() + ")";
	}


	public ScriptLog() {
	}


	public ScriptLog(final String level, final String value) {
		this.level = level;
		this.value = value;
	}
}
