// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dsaonline.rest.controller;

import de.failender.dsaonline.rest.dto.StatisticEntry;
import de.failender.dsaonline.security.AuthorizationService;
import de.failender.dsaonline.service.AdministrationService;
import de.failender.dsaonline.service.export.ExportService;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import de.failender.dsaonline.service.MeisterService;

@RestController
@RequestMapping("api/administration")
public class AdministrationController {
	private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AdministrationController.class);
	private final ExportService exportService;
	private final AdministrationService administrationService;
	private final AuthorizationService authorizationService;
	private final MeisterService meisterService;

	public AdministrationController(ExportService exportService, AdministrationService administrationService, AuthorizationService authorizationService, MeisterService meisterService) {
		this.exportService = exportService;
		this.administrationService = administrationService;
		this.authorizationService = authorizationService;
		this.meisterService = meisterService;
	}

	@PostMapping("import/full")
	public void provideFullImport(@RequestParam("file") MultipartFile file) {
		try {
			exportService.provideFullImport(file.getInputStream());
		} catch (AccessDeniedException e) {
			log.error(e.getMessage());
			throw e;
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@GetMapping("export/full")
	public void provideFullExport(HttpServletResponse response, @RequestParam String username, @RequestParam String password) {
		authorizationService.authenticate(password, username);
		exportService.provideFullExport(response);
	}

	@GetMapping("statistics")
	public List<StatisticEntry> getStatistics() {
		return administrationService.getStatistics();
	}
}
